'use client';

import { useTranslation } from '../../../lib/i18n-client';

interface AttributesAddAttributeFormProps {
  formData: { name: string };
  onFormDataChange: (data: { name: string }) => void;
  onSubmit: (event: React.FormEvent) => void;
  onCancel: () => void;
}

export function AttributesAddAttributeForm({
  formData,
  onFormDataChange,
  onSubmit,
  onCancel,
}: AttributesAddAttributeFormProps) {
  const { t } = useTranslation();

  return (
    <div className="mb-6 bg-white rounded-lg shadow-sm border border-gray-200 p-6">
      <h2 className="text-lg font-semibold text-gray-900 mb-4">
        {t('admin.attributes.createNewAttribute')}
      </h2>
      <form onSubmit={onSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('admin.attributes.name')}{' '}
            <span className="text-red-500">{t('admin.attributes.required')}</span>
          </label>
          <input
            type="text"
            value={formData.name}
            onChange={(e) => onFormDataChange({ ...formData, name: e.target.value })}
            placeholder={t('admin.attributes.namePlaceholder')}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-gray-900 focus:border-transparent"
            required
          />
          <p className="text-xs text-gray-500 mt-1">{t('admin.attributes.keyAutoGenerated')}</p>
        </div>

        <div className="flex gap-3 pt-2">
          <button
            type="submit"
            className="px-4 py-2 bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors"
          >
            {t('admin.attributes.createAttribute')}
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
          >
            {t('admin.attributes.cancel')}
          </button>
        </div>
      </form>
    </div>
  );
}
