import type { TranslationsJson } from "@/db/schema";
import { seedUuid } from "@/db/seed/seed-uuid";

type LocaleTriple = readonly [hy: string, en: string, ru: string];

type CategorySpec = {
  key: string;
  sortOrder: number;
  titles: LocaleTriple;
  slugs: LocaleTriple;
  basePrice: number;
  dishes: ReadonlyArray<LocaleTriple>;
};

export type SeedCatalogCategory = {
  id: string;
  sortOrder: number;
  status: "ACTIVE";
  translations: TranslationsJson;
  mediaId: string;
  objectKey: string;
};

export type SeedCatalogProduct = {
  id: string;
  categoryId: string;
  productCategoryId: string;
  mediaId: string;
  sku: string;
  sortOrder: number;
  priceAmount: number;
  compareAtAmount: number;
  objectKey: string;
  translations: TranslationsJson;
};

const PRODUCTS_PER_CATEGORY = 18;

/** Figma DEGUSTO-DEV-1 node 64:1946 — excluding «Բոլորը». */
const FIGMA_CATEGORIES: ReadonlyArray<CategorySpec> = [
  {
    key: "soups",
    sortOrder: 1,
    titles: ["Ապուրներ եւ տաք ուտեստներ", "Soups & hot dishes", "Супы и горячие блюда"],
    slugs: ["apurner", "soups", "supy"],
    basePrice: 1800,
    dishes: [
      ["Հարիսա", "Harissa", "Хариса"],
      ["Սպաս", "Spas", "Спас"],
      ["Բորշչ", "Borscht", "Борщ"],
      ["Տոլմա ապուր", "Tolma soup", "Суп толма"],
      ["Հավի ապուր", "Chicken soup", "Куриный суп"],
      ["Սնկով ապուր", "Mushroom soup", "Грибной суп"],
      ["Ոսպով ապուր", "Lentil soup", "Чечевичный суп"],
      ["Ձկան ապուր", "Fish soup", "Уха"],
      ["Բանջարեղենային", "Vegetable soup", "Овощной суп"],
      ["Խաշ", "Khash", "Хаш"],
      ["Կրեմ ապուր", "Cream soup", "Крем-суп"],
      ["Լապշա ապուր", "Noodle soup", "Суп с лапшой"],
      ["Տաք պլով", "Hot pilaf", "Горячий плов"],
      ["Տապակած կարտոֆիլ", "Fried potatoes", "Жареный картофель"],
      ["Շնիցել", "Schnitzel", "Шницель"],
      ["Կոտլետ", "Cutlet", "Котлета"],
      ["Տապակած հավ", "Fried chicken", "Жареная курица"],
      ["Մսով ռագու", "Meat stew", "Мясное рагу"],
    ],
  },
  {
    key: "salads",
    sortOrder: 2,
    titles: ["Աղցաններ", "Salads", "Салаты"],
    slugs: ["aghaner", "salads", "salaty"],
    basePrice: 1500,
    dishes: [
      ["Հունական աղցան", "Greek salad", "Греческий салат"],
      ["Ցեզար", "Caesar", "Цезарь"],
      ["Օլիվյե", "Olivier", "Оливье"],
      ["Վինեգրետ", "Vinaigrette", "Винегрет"],
      ["Թարմ բանջարեղեն", "Fresh vegetables", "Свежие овощи"],
      ["Լոլիկով աղցան", "Tomato salad", "Салат с томатами"],
      ["Վարունգով աղցան", "Cucumber salad", "Салат с огурцами"],
      ["Կաղամբով աղցան", "Cabbage salad", "Капустный салат"],
      ["Ավոկադո աղցան", "Avocado salad", "Салат с авокадо"],
      ["Թունա աղցան", "Tuna salad", "Салат с тунцом"],
      ["Հավով աղցան", "Chicken salad", "Салат с курицей"],
      ["Պանրով աղցան", "Cheese salad", "Салат с сыром"],
      ["Շոփսկի", "Shopska", "Шопский"],
      ["Գարնանային", "Spring salad", "Весенний салат"],
      ["Տաք աղցան", "Warm salad", "Тёплый салат"],
      ["Նուռով աղցան", "Pomegranate salad", "Салат с гранатом"],
      ["Բազուկով աղցան", "Beet salad", "Свёкольный салат"],
      ["Խառը աղցան", "Mixed salad", "Смешанный салат"],
    ],
  },
  {
    key: "shawarma",
    sortOrder: 3,
    titles: ["Շաուրմա", "Shawarma", "Шаурма"],
    slugs: ["shawarma", "shawarma", "shaurma"],
    basePrice: 1600,
    dishes: [
      ["Հավի շաուրմա", "Chicken shawarma", "Куриная шаурма"],
      ["Խոզի շաուրմա", "Pork shawarma", "Свиная шаурма"],
      ["Տավարի շաուրմա", "Beef shawarma", "Говяжья шаурма"],
      ["Խառը շաուրմա", "Mixed shawarma", "Смешанная шаурма"],
      ["Պանրով շաուրմա", "Cheese shawarma", "Шаурма с сыром"],
      ["Կծու շաուրմա", "Spicy shawarma", "Острая шаурма"],
      ["Մեծ շաուրմա", "Large shawarma", "Большая шаурма"],
      ["Մինի շաուրմա", "Mini shawarma", "Мини-шаурма"],
      ["Դաբլ շաուրմա", "Double shawarma", "Двойная шаурма"],
      ["Բանջարեղենային", "Veggie shawarma", "Овощная шаурма"],
      ["Սոուսով շաուրմա", "Sauce shawarma", "Шаурма с соусом"],
      ["Ֆրիով շաուրմա", "Shawarma fries", "Шаурма с фри"],
      ["Գրիլ շաուրմա", "Grill shawarma", "Гриль-шаурма"],
      ["Հատուկ շաուրմա", "Special shawarma", "Особая шаурма"],
      ["Լավաշով շաուրմա", "Lavash shawarma", "Шаурма в лаваше"],
      ["Պիտայով շաուրմա", "Pita shawarma", "Шаурма в пите"],
      ["Թուրքական", "Turkish shawarma", "Турецкая шаурма"],
      ["Դեգուստո շաուրմա", "Degusto shawarma", "Шаурма Degusto"],
    ],
  },
  {
    key: "pizza",
    sortOrder: 4,
    titles: ["Պիցցա", "Pizza", "Пицца"],
    slugs: ["pizza", "pizza", "pitstsa"],
    basePrice: 2500,
    dishes: [
      ["Մարգարիտա", "Margherita", "Маргарита"],
      ["Պեպերոնի", "Pepperoni", "Пепперони"],
      ["Չորս պանիր", "Four cheese", "Четыре сыра"],
      ["Հավով պիցցա", "Chicken pizza", "Пицца с курицей"],
      ["Սնկով պիցցա", "Mushroom pizza", "Пицца с грибами"],
      ["Մսային", "Meat pizza", "Мясная"],
      ["Բանջարեղենային", "Veggie pizza", "Овощная"],
      ["Հավայական", "Hawaiian", "Гавайская"],
      ["Կապրիչոզա", "Capricciosa", "Капричоза"],
      ["Դիաբլո", "Diablo", "Диабло"],
      ["Բարբեկյու", "BBQ pizza", "Барбекю"],
      ["Ծովամթերք", "Seafood pizza", "С морепродуктами"],
      ["Պարմա", "Parma pizza", "Парма"],
      ["Կալցոնե", "Calzone", "Кальцоне"],
      ["Մինի պիցցա", "Mini pizza", "Мини-пицца"],
      ["Ընտանեկան", "Family pizza", "Семейная"],
      ["Պիցցա ռոլլ", "Pizza roll", "Пицца-ролл"],
      ["Դեգուստո պիցցա", "Degusto pizza", "Пицца Degusto"],
    ],
  },
  {
    key: "lahmajoun",
    sortOrder: 5,
    titles: ["Լահմաջո", "Lahmajoun", "Лахмаджун"],
    slugs: ["lahmajoun", "lahmajoun", "lakhmadzhun"],
    basePrice: 900,
    dishes: [
      ["Դասական լահմաջո", "Classic lahmajoun", "Классический"],
      ["Կծու լահմաջո", "Spicy lahmajoun", "Острый"],
      ["Պանրով լահմաջո", "Cheese lahmajoun", "С сыром"],
      ["Բանջարեղենային", "Veggie lahmajoun", "Овощной"],
      ["Մսային լահմաջո", "Meat lahmajoun", "Мясной"],
      ["Կրկնակի", "Double lahmajoun", "Двойной"],
      ["Մինի լահմաջո", "Mini lahmajoun", "Мини"],
      ["Հավով լահմաջո", "Chicken lahmajoun", "С курицей"],
      ["Սոուսով", "With sauce", "С соусом"],
      ["Թարմ խոտաբույսերով", "Herb lahmajoun", "С зеленью"],
      ["Լոլիկով", "Tomato lahmajoun", "С томатами"],
      ["Սխտորով", "Garlic lahmajoun", "С чесноком"],
      ["Պղպեղով", "Pepper lahmajoun", "С перцем"],
      ["Խառը լահմաջո", "Mixed lahmajoun", "Смешанный"],
      ["Ընտանեկան սեթ", "Family set", "Семейный сет"],
      ["Լահմաջո կոմբո", "Lahmajoun combo", "Комбо"],
      ["Տապակած լահմաջո", "Crispy lahmajoun", "Хрустящий"],
      ["Դեգուստո լահմաջո", "Degusto lahmajoun", "Лахмаджун Degusto"],
    ],
  },
  {
    key: "khachapuri",
    sortOrder: 6,
    titles: ["Վրացական Խաչապուրի", "Georgian Khachapuri", "Грузинский хачапури"],
    slugs: ["khachapuri", "khachapuri", "khachapuri"],
    basePrice: 2200,
    dishes: [
      ["Աջարական", "Adjarian", "Аджарский"],
      ["Իմերեթական", "Imeretian", "Имеретинский"],
      ["Մեգրելական", "Megrelian", "Мегрельский"],
      ["Պենովանի", "Penovani", "Пеновани"],
      ["Լոբիանի", "Lobiani", "Лобиани"],
      ["Խաչապուրի պանրով", "Cheese khachapuri", "С сыром"],
      ["Խաչապուրի ձվով", "Egg khachapuri", "С яйцом"],
      ["Մինի խաչապուրի", "Mini khachapuri", "Мини"],
      ["Դաբլ պանիր", "Double cheese", "Двойной сыр"],
      ["Սնկով խաչապուրի", "Mushroom khachapuri", "С грибами"],
      ["Մսով խաչապուրի", "Meat khachapuri", "С мясом"],
      ["Կծու խաչապուրի", "Spicy khachapuri", "Острый"],
      ["Ընտանեկան", "Family khachapuri", "Семейный"],
      ["Խաչապուրի սեթ", "Khachapuri set", "Сет"],
      ["Թխված խաչապուրի", "Baked khachapuri", "Печёный"],
      ["Գրիլ խաչապուրի", "Grill khachapuri", "Гриль"],
      ["Հատուկ խաչապուրի", "Special khachapuri", "Особый"],
      ["Դեգուստո խաչապուրի", "Degusto khachapuri", "Хачапури Degusto"],
    ],
  },
  {
    key: "khorovats",
    sortOrder: 7,
    titles: ["Խորոված", "Barbecue", "Шашлык"],
    slugs: ["khorovats", "khorovats", "khorovats"],
    basePrice: 3500,
    dishes: [
      ["Խոզի խորոված", "Pork khorovats", "Свиной шашлык"],
      ["Տավարի խորոված", "Beef khorovats", "Говяжий шашлык"],
      ["Հավի խորոված", "Chicken khorovats", "Куриный шашлык"],
      ["Գառան խորոված", "Lamb khorovats", "Бараний шашлык"],
      ["Լյարդի խորոված", "Liver khorovats", "Шашлык из печени"],
      ["Բանջարեղենային", "Veggie grill", "Овощной гриль"],
      ["Խառը խորոված", "Mixed khorovats", "Ассорти"],
      ["Քյաբաբ", "Kebab", "Кебаб"],
      ["Լուլա քյաբաբ", "Lula kebab", "Люля-кебаб"],
      ["Նրբերանգ", "Assorted grill", "Ассорти гриль"],
      ["Կողոսկր", "Ribs", "Рёбра"],
      ["Հավի թևիկներ", "Chicken wings", "Крылышки"],
      ["Շամփուր միս", "Skewer meat", "Мясо на шампуре"],
      ["Գրիլ երշիկ", "Grill sausage", "Колбаски гриль"],
      ["Խորոված սեթ", "BBQ set", "Сет шашлыка"],
      ["Ընտանեկան խորոված", "Family BBQ", "Семейный шашлык"],
      ["Կծու խորոված", "Spicy BBQ", "Острый шашлык"],
      ["Դեգուստո խորոված", "Degusto BBQ", "Шашлык Degusto"],
    ],
  },
  {
    key: "khinkali",
    sortOrder: 8,
    titles: ["Խինկալի", "Khinkali", "Хинкали"],
    slugs: ["khinkali", "khinkali", "khinkali"],
    basePrice: 200,
    dishes: [
      ["Մսով խինկալի", "Meat khinkali", "С мясом"],
      ["Պանրով խինկալի", "Cheese khinkali", "С сыром"],
      ["Սնկով խինկալի", "Mushroom khinkali", "С грибами"],
      ["Խառը խինկալի", "Mixed khinkali", "Смешанные"],
      ["Կծու խինկալի", "Spicy khinkali", "Острые"],
      ["Թխված խինկալի", "Baked khinkali", "Печёные"],
      ["Տապակած խինկալի", "Fried khinkali", "Жареные"],
      ["Մինի խինկալի", "Mini khinkali", "Мини"],
      ["Խինկալի 5 հատ", "Khinkali x5", "Хинкали x5"],
      ["Խինկալի 10 հատ", "Khinkali x10", "Хинкали x10"],
      ["Խինկալի 15 հատ", "Khinkali x15", "Хинкали x15"],
      ["Գառան խինկալի", "Lamb khinkali", "С бараниной"],
      ["Հավով խինկալի", "Chicken khinkali", "С курицей"],
      ["Կանաչիով", "Herb khinkali", "С зеленью"],
      ["Խինկալի սեթ", "Khinkali set", "Сет"],
      ["Հատուկ խինկալի", "Special khinkali", "Особые"],
      ["Կրեմով խինկալի", "Cream khinkali", "Со сливками"],
      ["Դեգուստո խինկալի", "Degusto khinkali", "Хинкали Degusto"],
    ],
  },
  {
    key: "stuffed-potato",
    sortOrder: 9,
    titles: ["Լցոնած կարտոֆիլ", "Stuffed potatoes", "Фаршированный картофель"],
    slugs: ["ltonats-kartofil", "stuffed-potato", "farshirovannyj-kartofel"],
    basePrice: 1400,
    dishes: [
      ["Պանրով կարտոֆիլ", "Cheese potato", "С сыром"],
      ["Մսով կարտոֆիլ", "Meat potato", "С мясом"],
      ["Սնկով կարտոֆիլ", "Mushroom potato", "С грибами"],
      ["Բեկոնով", "Bacon potato", "С беконом"],
      ["Բանջարեղենային", "Veggie potato", "Овощной"],
      ["Կրկնակի պանիր", "Double cheese", "Двойной сыр"],
      ["Կծու կարտոֆիլ", "Spicy potato", "Острый"],
      ["Հավով կարտոֆիլ", "Chicken potato", "С курицей"],
      ["Խառը լցոնում", "Mixed stuffing", "Смешанная начинка"],
      ["Սոուսով կարտոֆիլ", "Potato with sauce", "С соусом"],
      ["Մինի կարտոֆիլ", "Mini potato", "Мини"],
      ["Ընտանեկան", "Family potato", "Семейный"],
      ["Գրիլ կարտոֆիլ", "Grill potato", "Гриль"],
      ["Թխված կարտոֆիլ", "Baked potato", "Печёный"],
      ["Կարտոֆիլ սեթ", "Potato set", "Сет"],
      ["Պղպեղով", "Pepper potato", "С перцем"],
      ["Հատուկ լցոնում", "Special stuffing", "Особая начинка"],
      ["Դեգուստո կարտոֆիլ", "Degusto potato", "Картофель Degusto"],
    ],
  },
  {
    key: "burgers",
    sortOrder: 10,
    titles: ["Բուրգերներ եւ սենդվիչներ", "Burgers & sandwiches", "Бургеры и сэндвичи"],
    slugs: ["burgers-sandwiches", "burgers-sandwiches", "burgery-sendvichi"],
    basePrice: 1800,
    dishes: [
      ["Դասական բուրգեր", "Classic burger", "Классический бургер"],
      ["Չիզբուրգեր", "Cheeseburger", "Чизбургер"],
      ["Դաբլ չիզ", "Double cheese", "Двойной чиз"],
      ["Կծու բուրգեր", "Spicy burger", "Острый бургер"],
      ["Հավի բուրգեր", "Chicken burger", "Куриный бургер"],
      ["Բեկոն բուրգեր", "Bacon burger", "Бургер с беконом"],
      ["Բանջարեղենային", "Veggie burger", "Овощной бургер"],
      ["Կլաբ սենդվիչ", "Club sandwich", "Клаб-сэндвич"],
      ["Հավի սենդվիչ", "Chicken sandwich", "Куриный сэндвич"],
      ["Պանրով սենդվիչ", "Cheese sandwich", "Сырный сэндвич"],
      ["Թունա սենդվիչ", "Tuna sandwich", "Сэндвич с тунцом"],
      ["Հոթ դոգ", "Hot dog", "Хот-дог"],
      ["Գրիլ սենդվիչ", "Grill sandwich", "Гриль-сэндвич"],
      ["Դելյուքս բուրգեր", "Deluxe burger", "Делюкс бургер"],
      ["Մինի բուրգեր", "Mini burger", "Мини-бургер"],
      ["Բուրգեր կոմբո", "Burger combo", "Комбо бургер"],
      ["Ձվով բուրգեր", "Egg burger", "Бургер с яйцом"],
      ["Դեգուստո բուրգեր", "Degusto burger", "Бургер Degusto"],
    ],
  },
  {
    key: "pies-crepes",
    sortOrder: 11,
    titles: ["Կարկանդակներ եւ նրբաբլիթներ", "Pies & crepes", "Пирожки и блины"],
    slugs: ["karkandakner", "pies-crepes", "pirozhki-bliny"],
    basePrice: 800,
    dishes: [
      ["Մսով կարկանդակ", "Meat pie", "Пирожок с мясом"],
      ["Պանրով կարկանդակ", "Cheese pie", "Пирожок с сыром"],
      ["Կարտոֆիլով", "Potato pie", "С картофелем"],
      ["Կաղամբով", "Cabbage pie", "С капустой"],
      ["Սնկով կարկանդակ", "Mushroom pie", "С грибами"],
      ["Քաղցր կարկանդակ", "Sweet pie", "Сладкий пирожок"],
      ["Խնձորով", "Apple pie", "С яблоком"],
      ["Նրբաբլիթ մսով", "Meat crepe", "Блин с мясом"],
      ["Նրբաբլիթ պանրով", "Cheese crepe", "Блин с сыром"],
      ["Նրբաբլիթ մեղրով", "Honey crepe", "Блин с мёдом"],
      ["Նրբաբլիթ մուրաբայով", "Jam crepe", "Блин с вареньем"],
      ["Շոկոլադե նրբաբլիթ", "Chocolate crepe", "Шоколадный блин"],
      ["Խառը կարկանդակներ", "Mixed pies", "Ассорти пирожков"],
      ["Մինի կարկանդակ", "Mini pie", "Мини-пирожок"],
      ["Թխված կարկանդակ", "Baked pie", "Печёный пирожок"],
      ["Տապակած կարկանդակ", "Fried pie", "Жареный пирожок"],
      ["Նրբաբլիթ սեթ", "Crepe set", "Сет блинов"],
      ["Դեգուստո կարկանդակ", "Degusto pie", "Пирожок Degusto"],
    ],
  },
  {
    key: "combo",
    sortOrder: 12,
    titles: ["Կոմբո փաթեթներ", "Combo packs", "Комбо-пакеты"],
    slugs: ["combo-paketner", "combo-packs", "kombo-pakety"],
    basePrice: 4500,
    dishes: [
      ["Ընտանեկան կոմբո", "Family combo", "Семейное комбо"],
      ["Բուրգեր կոմբո", "Burger combo", "Комбо бургер"],
      ["Պիցցա կոմբո", "Pizza combo", "Комбо пицца"],
      ["Շաուրմա կոմբո", "Shawarma combo", "Комбо шаурма"],
      ["Խորոված կոմբո", "BBQ combo", "Комбо шашлык"],
      ["Լանչ կոմբո", "Lunch combo", "Обеденное комбо"],
      ["Զույգերի կոմբո", "Couple combo", "Комбо для двоих"],
      ["Կծու կոմբո", "Spicy combo", "Острое комбо"],
      ["Մանկական կոմբո", "Kids combo", "Детское комбо"],
      ["Սուշի կոմբո", "Sushi combo", "Суши-комбо"],
      ["Նախաճաշ կոմբո", "Breakfast combo", "Завтрак-комбо"],
      ["Գրիլ կոմբո", "Grill combo", "Гриль-комбо"],
      ["Մեգա կոմբո", "Mega combo", "Мега-комбо"],
      ["Թեթև կոմբո", "Light combo", "Лёгкое комбо"],
      ["Պահքի կոմբո", "Lenten combo", "Постное комбо"],
      ["Խինկալի կոմբո", "Khinkali combo", "Комбо хинкали"],
      ["Պաստա կոմբո", "Pasta combo", "Комбо паста"],
      ["Դեգուստո կոմբո", "Degusto combo", "Комбо Degusto"],
    ],
  },
  {
    key: "lunch-boxes",
    sortOrder: 13,
    titles: ["Լանչ Բոքսեր", "Lunch Boxes", "Ланч-боксы"],
    slugs: ["lunch-boxes", "lunch-boxes", "lanch-boksy"],
    basePrice: 3200,
    dishes: [
      ["Դասական լանչ", "Classic lunch", "Классический ланч"],
      ["Հավով լանչ", "Chicken lunch", "Ланч с курицей"],
      ["Մսով լանչ", "Meat lunch", "Ланч с мясом"],
      ["Ձկան լանչ", "Fish lunch", "Ланч с рыбой"],
      ["Բանջարեղենային", "Veggie lunch", "Овощной ланч"],
      ["Պահքի լանչ", "Lenten lunch", "Постный ланч"],
      ["Ասիական լանչ", "Asian lunch", "Азиатский ланч"],
      ["Պաստա լանչ", "Pasta lunch", "Ланч с пастой"],
      ["Սալաթ լանչ", "Salad lunch", "Ланч с салатом"],
      ["Գրիլ լանչ", "Grill lunch", "Гриль-ланч"],
      ["Կծու լանչ", "Spicy lunch", "Острый ланч"],
      ["Թեթև լանչ", "Light lunch", "Лёгкий ланч"],
      ["Պրոտեին լանչ", "Protein lunch", "Протеиновый ланч"],
      ["Օֆիս լանչ", "Office lunch", "Офисный ланч"],
      ["Մեծ լանչ", "Large lunch", "Большой ланч"],
      ["Մինի լանչ", "Mini lunch", "Мини-ланч"],
      ["Շեֆի լանչ", "Chef lunch", "Ланч шефа"],
      ["Դեգուստո լանչ", "Degusto lunch", "Ланч Degusto"],
    ],
  },
  {
    key: "grill-smoked",
    sortOrder: 14,
    titles: ["Գրիլ եւ ապխտած արտադրանքներ", "Grill & smoked", "Гриль и копчёности"],
    slugs: ["gril-apxtats", "grill-smoked", "gril-kopchenosti"],
    basePrice: 2800,
    dishes: [
      ["Ապխտած հավ", "Smoked chicken", "Копчёная курица"],
      ["Ապխտած միս", "Smoked meat", "Копчёное мясо"],
      ["Ապխտած երշիկ", "Smoked sausage", "Копчёная колбаса"],
      ["Գրիլ կողոսկր", "Grill ribs", "Рёбра гриль"],
      ["Գրիլ հավ", "Grill chicken", "Курица гриль"],
      ["Գրիլ բանջարեղեն", "Grill vegetables", "Овощи гриль"],
      ["Ապխտած պանիր", "Smoked cheese", "Копчёный сыр"],
      ["Գրիլ ձուկ", "Grill fish", "Рыба гриль"],
      ["Ապխտած սաղմոն", "Smoked salmon", "Копчёный лосось"],
      ["Գրիլ երշիկներ", "Grill sausages", "Колбаски гриль"],
      ["Ապխտած կողոսկր", "Smoked ribs", "Копчёные рёбра"],
      ["Գրիլ շամփուր", "Grill skewer", "Шампур гриль"],
      ["Ապխտած սեթ", "Smoked set", "Копчёный сет"],
      ["Գրիլ սեթ", "Grill set", "Гриль-сет"],
      ["Կծու գրիլ", "Spicy grill", "Острый гриль"],
      ["Հատուկ ապխտած", "Special smoked", "Особое копчение"],
      ["Խառը գրիլ", "Mixed grill", "Смешанный гриль"],
      ["Դեգուստո գրիլ", "Degusto grill", "Гриль Degusto"],
    ],
  },
  {
    key: "bread",
    sortOrder: 15,
    titles: ["Հաց", "Bread", "Хлеб"],
    slugs: ["hats", "bread", "khleb"],
    basePrice: 400,
    dishes: [
      ["Լավաշ", "Lavash", "Лаваш"],
      ["Մատնաքաշ", "Matnakash", "Матнакаш"],
      ["Սև հաց", "Black bread", "Чёрный хлеб"],
      ["Սպիտակ հաց", "White bread", "Белый хлеб"],
      ["Հացաբուլկի", "Bread rolls", "Булочки"],
      ["Թարմ բագետ", "Baguette", "Багет"],
      ["Պիտա", "Pita", "Пита"],
      ["Տորտիլա", "Tortilla", "Тортилья"],
      ["Սխտորով հաց", "Garlic bread", "Чесночный хлеб"],
      ["Պանրով հաց", "Cheese bread", "Хлеб с сыром"],
      ["Հացիկներ", "Buns", "Булочки мини"],
      ["Ամբողջահատիկ", "Whole grain", "Цельнозерновой"],
      ["Թխված հաց", "Fresh baked", "Свежая выпечка"],
      ["Գյուղական հաց", "Village bread", "Деревенский хлеб"],
      ["Հաց սեթ", "Bread set", "Сет хлеба"],
      ["Չորահաց", "Crackers", "Сухари"],
      ["Բրիոշ", "Brioche", "Бриошь"],
      ["Դեգուստո հաց", "Degusto bread", "Хлеб Degusto"],
    ],
  },
  {
    key: "pastry",
    sortOrder: 16,
    titles: ["Խմորեղեն", "Pastry", "Выпечка"],
    slugs: ["khmoreghen", "pastry", "vypechka"],
    basePrice: 700,
    dishes: [
      ["Կրուասան", "Croissant", "Круассан"],
      ["Պանրով կրուասան", "Cheese croissant", "Круассан с сыром"],
      ["Շոկոլադե կրուասան", "Chocolate croissant", "Шоколадный круассан"],
      ["Բուլկի", "Sweet bun", "Сладкая булочка"],
      ["Մեղրով խմորեղեն", "Honey pastry", "Выпечка с мёдом"],
      ["Ընկույզով", "Nut pastry", "С орехами"],
      ["Կաթնաշոռով", "Cottage cheese pastry", "С творогом"],
      ["Մուրաբայով", "Jam pastry", "С вареньем"],
      ["Պաղպաղակով բուլկի", "Ice cream bun", "Булочка с мороженым"],
      ["Թխվածքաբլիթ", "Cookie", "Печенье"],
      ["Էկլեր", "Eclair", "Эклер"],
      ["Միլֆեյ", "Millefeuille", "Мильфей"],
      ["Դանիշ", "Danish", "Датская выпечка"],
      ["Պոնչիկ", "Donut", "Пончик"],
      ["Մաֆին", "Muffin", "Маффин"],
      ["Խմորեղեն սեթ", "Pastry set", "Сет выпечки"],
      ["Թարմ խմորեղեն", "Fresh pastry", "Свежая выпечка"],
      ["Դեգուստո խմորեղեն", "Degusto pastry", "Выпечка Degusto"],
    ],
  },
  {
    key: "omelette",
    sortOrder: 17,
    titles: ["Ձվածեղ", "Omelette", "Омлет"],
    slugs: ["dzvategh", "omelette", "omlet"],
    basePrice: 1200,
    dishes: [
      ["Դասական ձվածեղ", "Classic omelette", "Классический омлет"],
      ["Պանրով ձվածեղ", "Cheese omelette", "Омлет с сыром"],
      ["Բեկոնով", "Bacon omelette", "С беконом"],
      ["Սնկով ձվածեղ", "Mushroom omelette", "С грибами"],
      ["Բանջարեղենային", "Veggie omelette", "Овощной омлет"],
      ["Խառը ձվածեղ", "Mixed omelette", "Смешанный омлет"],
      ["Կծու ձվածեղ", "Spicy omelette", "Острый омлет"],
      ["Նրբերշիկով", "Sausage omelette", "С сосисками"],
      ["Պոմիդորով", "Tomato omelette", "С помидорами"],
      ["Կանաչիով", "Herb omelette", "С зеленью"],
      ["Դաբլ ձվածեղ", "Double omelette", "Двойной омлет"],
      ["Ձվածեղ հացով", "Omelette toast", "Омлет с тостом"],
      ["Շակշուկա", "Shakshuka", "Шакшука"],
      ["Տապակած ձու", "Fried eggs", "Яичница"],
      ["Խաշած ձու", "Boiled eggs", "Варёные яйца"],
      ["Ձվածեղ սեթ", "Omelette set", "Сет омлета"],
      ["Նախաճաշ ձվածեղ", "Breakfast omelette", "Завтрак-омлет"],
      ["Դեգուստո ձվածեղ", "Degusto omelette", "Омлет Degusto"],
    ],
  },
  {
    key: "lenten",
    sortOrder: 18,
    titles: ["Պահքի ուտեստներ", "Lenten dishes", "Постные блюда"],
    slugs: ["pahqi", "lenten", "postnye"],
    basePrice: 1300,
    dishes: [
      ["Պահքի աղցան", "Lenten salad", "Постный салат"],
      ["Պահքի ապուր", "Lenten soup", "Постный суп"],
      ["Բանջարեղենային տոլմա", "Veggie tolma", "Овощная толма"],
      ["Ոսպով ուտեստ", "Lentil dish", "Блюдо из чечевицы"],
      ["Սնկով ուտեստ", "Mushroom dish", "Блюдо с грибами"],
      ["Պահքի պլով", "Lenten pilaf", "Постный плов"],
      ["Բանջարեղենային խորոված", "Veggie BBQ", "Овощной шашлык"],
      ["Պահքի պաստա", "Lenten pasta", "Постная паста"],
      ["Պահքի պիցցա", "Lenten pizza", "Постная пицца"],
      ["Պահքի շաուրմա", "Lenten shawarma", "Постная шаурма"],
      ["Խաշուած բանջարեղեն", "Stewed vegetables", "Тушёные овощи"],
      ["Պահքի կոմբո", "Lenten combo", "Постное комбо"],
      ["Պահքի լանչ", "Lenten lunch", "Постный ланч"],
      ["Նուտով ուտեստ", "Chickpea dish", "Блюдо из нута"],
      ["Բրինձ բանջարեղենով", "Rice & veggies", "Рис с овощами"],
      ["Պահքի սոուս", "Lenten sauce", "Постный соус"],
      ["Թարմ մրգեր", "Fresh fruit", "Свежие фрукты"],
      ["Դեգուստո պահք", "Degusto lenten", "Постное Degusto"],
    ],
  },
  {
    key: "sushi",
    sortOrder: 19,
    titles: ["Ասիական խոհանոց (Սուշի)", "Asian cuisine (Sushi)", "Азиатская кухня (Суши)"],
    slugs: ["asian-sushi", "asian-sushi", "aziatskaya-sushi"],
    basePrice: 4000,
    dishes: [
      ["Ֆիլադելֆիա", "Philadelphia", "Филадельфия"],
      ["Կալիֆորնիա", "California", "Калифорния"],
      ["Դրակոն", "Dragon roll", "Дракон"],
      ["Սաղմոն ռոլլ", "Salmon roll", "Ролл с лососем"],
      ["Թունա ռոլլ", "Tuna roll", "Ролл с тунцом"],
      ["Բանջարեղենային ռոլլ", "Veggie roll", "Овощной ролл"],
      ["Տեմպուրա ռոլլ", "Tempura roll", "Темпура ролл"],
      ["Սուշի սեթ", "Sushi set", "Суши-сет"],
      ["Սաշիմի սեթ", "Sashimi set", "Сашими-сет"],
      ["Նիգիրի սեթ", "Nigiri set", "Нигири-сет"],
      ["Վասաբիով ռոլլ", "Wasabi roll", "Ролл с васаби"],
      ["Կծու սաղմոն", "Spicy salmon", "Острый лосось"],
      ["Ծովախեցգետին", "Shrimp roll", "Ролл с креветкой"],
      ["Ունագի ռոլլ", "Unagi roll", "Унаги ролл"],
      ["Մեգա սուշի", "Mega sushi", "Мега-суши"],
      ["Մինի սուշի", "Mini sushi", "Мини-суши"],
      ["Ասիական վոկ", "Asian wok", "Азиатский вок"],
      ["Դեգուստո սուշի", "Degusto sushi", "Суши Degusto"],
    ],
  },
  {
    key: "pasta",
    sortOrder: 20,
    titles: ["Պաստաներ", "Pastas", "Пасты"],
    slugs: ["pastaner", "pastas", "pasty"],
    basePrice: 2200,
    dishes: [
      ["Կարբոնարա", "Carbonara", "Карбонара"],
      ["Բոլոնեզ", "Bolognese", "Болоньезе"],
      ["Ալֆրեդո", "Alfredo", "Альфредо"],
      ["Պեստո պաստա", "Pesto pasta", "Паста песто"],
      ["Ծովամթերք պաստա", "Seafood pasta", "Паста с морепродуктами"],
      ["Սնկով պաստա", "Mushroom pasta", "Паста с грибами"],
      ["Հավով պաստա", "Chicken pasta", "Паста с курицей"],
      ["Բանջարեղենային", "Veggie pasta", "Овощная паста"],
      ["Լազանիա", "Lasagna", "Лазанья"],
      ["Պենե արաբիատա", "Penneh Arrabbiata", "Пенне аррабиата"],
      ["Սպագետտի", "Spaghetti", "Спагетти"],
      ["Ֆետուչինի", "Fettuccine", "Феттуччине"],
      ["Ռավիոլի", "Ravioli", "Равиоли"],
      ["Պաստա սեթ", "Pasta set", "Сет пасты"],
      ["Կծու պաստա", "Spicy pasta", "Острая паста"],
      ["Պանրով պաստա", "Cheese pasta", "Паста с сыром"],
      ["Թխված պաստա", "Baked pasta", "Запечённая паста"],
      ["Դեգուստո պաստա", "Degusto pasta", "Паста Degusto"],
    ],
  },
  {
    key: "sauces",
    sortOrder: 21,
    titles: ["Սոուսներ", "Sauces", "Соусы"],
    slugs: ["sousner", "sauces", "sousy"],
    basePrice: 500,
    dishes: [
      ["Կետչուպ", "Ketchup", "Кетчуп"],
      ["Մայոնեզ", "Mayonnaise", "Майонез"],
      ["Սխտորի սոուս", "Garlic sauce", "Чесночный соус"],
      ["Կծու սոուս", "Spicy sauce", "Острый соус"],
      ["Բարբեկյու սոուս", "BBQ sauce", "Соус барбекю"],
      ["Պանրի սոուս", "Cheese sauce", "Сырный соус"],
      ["Մանանեխ", "Mustard", "Горчица"],
      ["Սոյայի սոուս", "Soy sauce", "Соевый соус"],
      ["Թերիյակի", "Teriyaki", "Терияки"],
      ["Վասաբի", "Wasabi", "Васаби"],
      ["Իմբիրային", "Ginger sauce", "Имбирный соус"],
      ["Թառախի սոուս", "Tarator", "Таратор"],
      ["Նուշի սոուս", "Nut sauce", "Ореховый соус"],
      ["Լոլիկի սոուս", "Tomato sauce", "Томатный соус"],
      ["Կրեմ սոուս", "Cream sauce", "Сливочный соус"],
      ["Հատուկ սոուս", "Special sauce", "Особый соус"],
      ["Սոուսների սեթ", "Sauce set", "Сет соусов"],
      ["Դեգուստո սոուս", "Degusto sauce", "Соус Degusto"],
    ],
  },
  {
    key: "restaurant",
    sortOrder: 22,
    titles: ["Ռեստորան", "Restaurant", "Ресторан"],
    slugs: ["restoran", "restaurant", "restoran"],
    basePrice: 5000,
    dishes: [
      ["Շեֆի ուտեստ", "Chef special", "Блюдо шефа"],
      ["Տավարի սթեյք", "Beef steak", "Говяжий стейк"],
      ["Հավի ֆիլե", "Chicken fillet", "Куриное филе"],
      ["Ձկան ուտեստ", "Fish dish", "Рыбное блюдо"],
      ["Ծովամթերք սեթ", "Seafood set", "Сет морепродуктов"],
      ["Ռիսոտտո", "Risotto", "Ризотто"],
      ["Դակինգ դաք", "Peking duck", "Утка по-пекински"],
      ["Վինագրետ ռեստորան", "Restaurant salad", "Ресторанный салат"],
      ["Սուպ օրվա", "Soup of the day", "Суп дня"],
      ["Հիմնական ուտեստ", "Main course", "Основное блюдо"],
      ["Կողմնակի", "Side dish", "Гарнир"],
      ["Մանկական մենյու", "Kids menu", "Детское меню"],
      ["Վեգան ուտեստ", "Vegan dish", "Веганское блюдо"],
      ["Գուրմե սեթ", "Gourmet set", "Гурме-сет"],
      ["Երեկոյան մենյու", "Evening menu", "Вечернее меню"],
      ["Բիզնես լանչ", "Business lunch", "Бизнес-ланч"],
      ["Դեգուստացիոն", "Tasting menu", "Дегустационное"],
      ["Դեգուստո ռեստորան", "Degusto restaurant", "Ресторан Degusto"],
    ],
  },
  {
    key: "bar",
    sortOrder: 23,
    titles: ["Բար (Ալկոհոլ)", "Bar (Alcohol)", "Бар (Алкоголь)"],
    slugs: ["bar-alkohol", "bar-alcohol", "bar-alkogol"],
    basePrice: 2500,
    dishes: [
      ["Գարեջուր", "Beer", "Пиво"],
      ["Գինի կարմիր", "Red wine", "Красное вино"],
      ["Գինի սպիտակ", "White wine", "Белое вино"],
      ["Շամպայն", "Champagne", "Шампанское"],
      ["Վիսկի", "Whiskey", "Виски"],
      ["Օղի", "Vodka", "Водка"],
      ["Կոնյակ", "Cognac", "Коньяк"],
      ["Ռոմ", "Rum", "Ром"],
      ["Ջին", "Gin", "Джин"],
      ["Թեքիլա", "Tequila", "Текила"],
      ["Կոկտեյլ մոխիտո", "Mojito", "Мохито"],
      ["Կոկտեյլ մարգարիտա", "Margarita", "Маргарита"],
      ["Ապերոլ շպրից", "Aperol spritz", "Апероль шприц"],
      ["Լիկյոր", "Liqueur", "Ликёр"],
      ["Բար սեթ", "Bar set", "Барный сет"],
      ["Ոչ ալկոհոլային", "Non-alcoholic", "Безалкогольный"],
      ["Տաք գինի", "Mulled wine", "Глинтвейн"],
      ["Դեգուստո բար", "Degusto bar", "Бар Degusto"],
    ],
  },
  {
    key: "drinks",
    sortOrder: 24,
    titles: ["Հյութեր և Ըմպելիքներ", "Juices & drinks", "Соки и напитки"],
    slugs: ["hyuter-ympeliqner", "juices-drinks", "soki-napitki"],
    basePrice: 600,
    dishes: [
      ["Նարնջի հյութ", "Orange juice", "Апельсиновый сок"],
      ["Խնձորի հյութ", "Apple juice", "Яблочный сок"],
      ["Լիմոնադ", "Lemonade", "Лимонад"],
      ["Թարմ մրգահյութ", "Fresh juice", "Фреш"],
      ["Կոլա", "Cola", "Кола"],
      ["Հանքային ջուր", "Mineral water", "Минеральная вода"],
      ["Թեյ", "Tea", "Чай"],
      ["Սուրճ", "Coffee", "Кофе"],
      ["Կապուչինո", "Cappuccino", "Капучино"],
      ["Լատտե", "Latte", "Латте"],
      ["Սմուզի", "Smoothie", "Смузи"],
      ["Միլքշեյք", "Milkshake", "Молочный коктейль"],
      ["Կոմպոտ", "Kompot", "Компот"],
      ["Թան", "Tan", "Тан"],
      ["Այրան", "Ayran", "Айран"],
      ["Սառը թեյ", "Iced tea", "Холодный чай"],
      ["Էներգետիկ", "Energy drink", "Энергетик"],
      ["Դեգուստո ըմպելիք", "Degusto drink", "Напиток Degusto"],
    ],
  },
  {
    key: "semi-finished",
    sortOrder: 25,
    titles: ["Կիսաֆաբրիկատներ", "Semi-finished", "Полуфабрикаты"],
    slugs: ["kisafabrikatner", "semi-finished", "polufabrikaty"],
    basePrice: 1500,
    dishes: [
      ["Սառեցված խինկալի", "Frozen khinkali", "Хинкали замороженные"],
      ["Սառեցված պելմենի", "Frozen pelmeni", "Пельмени"],
      ["Սառեցված կոտլետ", "Frozen cutlets", "Котлеты"],
      ["Պիցցա խմոր", "Pizza dough", "Тесто для пиццы"],
      ["Լահմաջո խմոր", "Lahmajoun dough", "Тесто лахмаджун"],
      ["Պատրաստի միս", "Prepared meat", "Готовое мясо"],
      ["Մարինացված միս", "Marinated meat", "Маринованное мясо"],
      ["Սառեցված բանջարեղեն", "Frozen veggies", "Овощи замороженные"],
      ["Պատրաստի սոուս", "Ready sauce", "Готовый соус"],
      ["Խմորեղենի խմոր", "Pastry dough", "Тесто для выпечки"],
      ["Սառեցված շաուրմա", "Frozen shawarma", "Шаурма замороженная"],
      ["Կիսաֆաբրիկատ սեթ", "Semi-finished set", "Сет полуфабрикатов"],
      ["Տնական կիսաֆաբրիկատ", "Homemade semi", "Домашний полуфабрикат"],
      ["Սառեցված տոլմա", "Frozen tolma", "Толма замороженная"],
      ["Պատրաստի կոտլետ", "Ready cutlets", "Готовые котлеты"],
      ["Խմորի փաթեթ", "Dough pack", "Набор теста"],
      ["Մսի փաթեթ", "Meat pack", "Мясной набор"],
      ["Դեգուստո կիսաֆաբրիկատ", "Degusto semi", "Полуфабрикат Degusto"],
    ],
  },
  {
    key: "mexican",
    sortOrder: 26,
    titles: ["Մեքսիկական խոհանոց", "Mexican cuisine", "Мексиканская кухня"],
    slugs: ["mexican", "mexican", "meksikanskaya"],
    basePrice: 2000,
    dishes: [
      ["Թակո", "Taco", "Тако"],
      ["Բուրիտո", "Burrito", "Буррито"],
      ["Քեսադիլլա", "Quesadilla", "Кесадилья"],
      ["Նաչոս", "Nachos", "Начос"],
      ["Էնչիլադա", "Enchilada", "Энчилада"],
      ["Ֆախիտա", "Fajita", "Фахита"],
      ["Գուակամոլե", "Guacamole", "Гуакамоле"],
      ["Սալսա", "Salsa", "Сальса"],
      ["Հավի թակո", "Chicken taco", "Тако с курицей"],
      ["Տավարի բուրիտո", "Beef burrito", "Буррито с говядиной"],
      ["Բանջարեղենային թակո", "Veggie taco", "Овощное тако"],
      ["Կծու մեքսիկական", "Spicy Mexican", "Острое мексиканское"],
      ["Մեքսիկական սեթ", "Mexican set", "Мексиканский сет"],
      ["Չիլի կոն կարնե", "Chili con carne", "Чили кон карне"],
      ["Թակո սեթ", "Taco set", "Сет тако"],
      ["Մինի բուրիտո", "Mini burrito", "Мини-буррито"],
      ["Մեքսիկական կոմբո", "Mexican combo", "Мексиканское комбо"],
      ["Դեգուստո մեքսիկական", "Degusto Mexican", "Мексиканское Degusto"],
    ],
  },
];

const CATEGORY_ID_BASE = 0x110;
const PRODUCT_ID_BASE = 0x1000;
const PRODUCT_CATEGORY_ID_BASE = 0x4000;
const MEDIA_PRODUCT_ID_BASE = 0x6000;
const MEDIA_CATEGORY_ID_BASE = 0x9000;

function toTranslations(
  titles: LocaleTriple,
  slugs: LocaleTriple,
  description?: LocaleTriple,
): TranslationsJson {
  return {
    hy: {
      title: titles[0],
      slug: slugs[0],
      description: description?.[0] ?? titles[0],
    },
    en: {
      title: titles[1],
      slug: slugs[1],
      description: description?.[1] ?? titles[1],
    },
    ru: {
      title: titles[2],
      slug: slugs[2],
      description: description?.[2] ?? titles[2],
    },
  };
}

function buildCatalog(): {
  categories: SeedCatalogCategory[];
  products: SeedCatalogProduct[];
} {
  const categories: SeedCatalogCategory[] = [];
  const products: SeedCatalogProduct[] = [];
  let productIndex = 0;

  for (const [categoryIndex, spec] of FIGMA_CATEGORIES.entries()) {
    if (spec.dishes.length !== PRODUCTS_PER_CATEGORY) {
      throw new Error(
        `Category ${spec.key} must have ${PRODUCTS_PER_CATEGORY} dishes`,
      );
    }

    const categoryId = seedUuid(CATEGORY_ID_BASE + categoryIndex);
    categories.push({
      id: categoryId,
      sortOrder: spec.sortOrder,
      status: "ACTIVE",
      translations: toTranslations(spec.titles, spec.slugs),
      mediaId: seedUuid(MEDIA_CATEGORY_ID_BASE + categoryIndex),
      objectKey: `assets/categories/seed/${spec.key}.webp`,
    });

    for (const [dishIndex, dish] of spec.dishes.entries()) {
      const n = dishIndex + 1;
      const slugSuffix = `${spec.key}-${String(n).padStart(2, "0")}`;
      const priceAmount = spec.basePrice + dishIndex * 50;
      products.push({
        id: seedUuid(PRODUCT_ID_BASE + productIndex),
        categoryId,
        productCategoryId: seedUuid(PRODUCT_CATEGORY_ID_BASE + productIndex),
        mediaId: seedUuid(MEDIA_PRODUCT_ID_BASE + productIndex),
        sku: `DG-${spec.key.toUpperCase().replaceAll("-", "")}-${String(n).padStart(3, "0")}`,
        sortOrder: n,
        priceAmount,
        compareAtAmount: Math.round(priceAmount * 1.25),
        objectKey: `assets/products/seed/${slugSuffix}.webp`,
        translations: toTranslations(dish, [
          `${slugSuffix}-hy`,
          slugSuffix,
          `${slugSuffix}-ru`,
        ], dish),
      });
      productIndex += 1;
    }
  }

  return { categories, products };
}

export const seedFigmaCatalog = buildCatalog();
