import type { TranslationsJson } from "@/db/schema";

export type FigmaCategorySeed = {
  key: string;
  sortOrder: number;
  iconKey: string;
  translations: TranslationsJson;
  productTitles: ReadonlyArray<{
    hy: string;
    en: string;
    ru: string;
  }>;
};

const PRODUCTS_PER_CATEGORY = 18;

function productTitles(
  items: ReadonlyArray<{ hy: string; en: string; ru: string }>,
): ReadonlyArray<{ hy: string; en: string; ru: string }> {
  if (items.length >= PRODUCTS_PER_CATEGORY) {
    return items.slice(0, PRODUCTS_PER_CATEGORY);
  }

  const filled = [...items];
  let n = 1;
  while (filled.length < PRODUCTS_PER_CATEGORY) {
    const base = items[(n - 1) % items.length]!;
    filled.push({
      hy: `${base.hy} ${n + items.length}`,
      en: `${base.en} ${n + items.length}`,
      ru: `${base.ru} ${n + items.length}`,
    });
    n += 1;
  }
  return filled;
}

/** Categories from Figma node 64:1946 (excluding UI-only «Բոլորը»). */
export const figmaCatalogCategories: ReadonlyArray<FigmaCategorySeed> = [
  {
    key: "soups-hot-dishes",
    sortOrder: 1,
    iconKey: "assets/categories/icons/soups-hot-dishes.webp",
    translations: {
      hy: {
        slug: "apurner",
        title: "Ապուրներ եւ տաք ուտեստներ",
        description: "Ապուրներ և տաք ուտեստներ",
      },
      en: {
        slug: "soups-hot-dishes",
        title: "Soups & hot dishes",
        description: "Soups and hot dishes",
      },
      ru: {
        slug: "supy-goryachie",
        title: "Супы и горячие блюда",
        description: "Супы и горячие блюда",
      },
    },
    productTitles: productTitles([
      { hy: "Հարիսա", en: "Harissa", ru: "Хариса" },
      { hy: "Բորշչ", en: "Borscht", ru: "Борщ" },
      { hy: "Հավի ապուր", en: "Chicken soup", ru: "Куриный суп" },
      { hy: "Սպաս", en: "Spas", ru: "Спас" },
      { hy: "Ոսպապուր", en: "Lentil soup", ru: "Чечевичный суп" },
      { hy: "Սնկով ապուր", en: "Mushroom soup", ru: "Грибной суп" },
      { hy: "Թոփիկ", en: "Topik", ru: "Топик" },
      { hy: "Կոլոլակ", en: "Kololak", ru: "Колотак" },
      { hy: "Խաշ", en: "Khash", ru: "Хаш" },
      { hy: "Բանջարեղենային ապուր", en: "Vegetable soup", ru: "Овощной суп" },
      { hy: "Տոլմա տաք", en: "Hot tolma", ru: "Горячая толма" },
      { hy: "Մսով ռագու", en: "Meat stew", ru: "Мясное рагу" },
      { hy: "Պլով", en: "Pilaf", ru: "Плов" },
      { hy: "Չալաղաջ", en: "Chalagaj", ru: "Чалагадж" },
      { hy: "Տավարի շտրոգանով", en: "Beef stroganoff", ru: "Бефстроганов" },
      { hy: "Կաթով ապուր", en: "Milk soup", ru: "Молочный суп" },
      { hy: "Ձկան ապուր", en: "Fish soup", ru: "Уха" },
      { hy: "Գառան խորոված կաթսա", en: "Lamb casserole", ru: "Баранье рагу" },
    ]),
  },
  {
    key: "salads",
    sortOrder: 2,
    iconKey: "assets/categories/icons/salads.webp",
    translations: {
      hy: { slug: "aghaner", title: "Աղցաններ", description: "Թարմ աղցաններ" },
      en: { slug: "salads", title: "Salads", description: "Fresh salads" },
      ru: { slug: "salaty", title: "Салаты", description: "Свежие салаты" },
    },
    productTitles: productTitles([
      { hy: "Հունական աղցան", en: "Greek salad", ru: "Греческий салат" },
      { hy: "Կեսար", en: "Caesar", ru: "Цезарь" },
      { hy: "Օլիվյե", en: "Olivier", ru: "Оливье" },
      { hy: "Վինեգրետ", en: "Vinaigrette", ru: "Винегрет" },
      { hy: "Թարմ բանջարեղեն", en: "Fresh vegetables", ru: "Свежие овощи" },
      { hy: "Ավոկադո աղցան", en: "Avocado salad", ru: "Салат с авокадо" },
      { hy: "Թունա աղցան", en: "Tuna salad", ru: "Салат с тунцом" },
      { hy: "Հավով աղցան", en: "Chicken salad", ru: "Салат с курицей" },
      { hy: "Շաղգամ աղցան", en: "Beet salad", ru: "Свекольный салат" },
      { hy: "Կաղամբ աղցան", en: "Cabbage salad", ru: "Капустный салат" },
      { hy: "Լոլիկ-վարունգ", en: "Tomato cucumber", ru: "Помидоры-огурцы" },
      { hy: "Ֆետա աղցան", en: "Feta salad", ru: "Салат с фетой" },
      { hy: "Ծովամթերք աղցան", en: "Seafood salad", ru: "Салат с морепродуктами" },
      { hy: "Տաբուլե", en: "Tabbouleh", ru: "Табуле" },
      { hy: "Գրիլ բանջարեղեն", en: "Grilled veg salad", ru: "Салат с гриль-овощами" },
      { hy: "Մոցարելլա աղցան", en: "Mozzarella salad", ru: "Салат с моцареллой" },
      { hy: "Խնձոր աղցան", en: "Apple salad", ru: "Яблочный салат" },
      { hy: "Գազար աղցան", en: "Carrot salad", ru: "Морковный салат" },
    ]),
  },
  {
    key: "shawarma",
    sortOrder: 3,
    iconKey: "assets/categories/icons/shawarma.webp",
    translations: {
      hy: { slug: "shawarma", title: "Շաուրմա", description: "Շաուրմա" },
      en: { slug: "shawarma", title: "Shawarma", description: "Shawarma" },
      ru: { slug: "shaurma", title: "Шаурма", description: "Шаурма" },
    },
    productTitles: productTitles([
      { hy: "Հավի շաուրմա", en: "Chicken shawarma", ru: "Куриная шаурма" },
      { hy: "Տավարի շաուրմա", en: "Beef shawarma", ru: "Говяжья шаурма" },
      { hy: "Խառը շաուրմա", en: "Mixed shawarma", ru: "Смешанная шаурма" },
      { hy: "Մեծ շաուրմա", en: "Large shawarma", ru: "Большая шаурма" },
      { hy: "Փոքր շաուրմա", en: "Small shawarma", ru: "Маленькая шаурма" },
      { hy: "Պանրով շաուրմա", en: "Cheese shawarma", ru: "Шаурма с сыром" },
      { hy: "Կծու շաուրմա", en: "Spicy shawarma", ru: "Острая шаурма" },
      { hy: "Բանջարեղենային", en: "Veggie shawarma", ru: "Овощная шаурма" },
      { hy: "Դոներ բոքս", en: "Doner box", ru: "Донер бокс" },
      { hy: "Շաուրմա ֆրիով", en: "Shawarma with fries", ru: "Шаурма с картошкой" },
      { hy: "Գառան շաուրմա", en: "Lamb shawarma", ru: "Баранья шаурма" },
      { hy: "Դաբլ շաուրմա", en: "Double shawarma", ru: "Двойная шаурма" },
      { hy: "Սոուսով շաուրմա", en: "Sauce shawarma", ru: "Шаурма с соусом" },
      { hy: "Մինի շաուրմա", en: "Mini shawarma", ru: "Мини шаурма" },
      { hy: "Ֆիրմային շաուրմա", en: "Signature shawarma", ru: "Фирменная шаурма" },
      { hy: "Շաուրմա սալաթով", en: "Shawarma salad wrap", ru: "Шаурма-салат" },
      { hy: "Գրիլ շաուրմա", en: "Grill shawarma", ru: "Гриль шаурма" },
      { hy: "Շաուրմա պլատո", en: "Shawarma platter", ru: "Шаурма плато" },
    ]),
  },
  {
    key: "pizza",
    sortOrder: 4,
    iconKey: "assets/categories/icons/pizza.webp",
    translations: {
      hy: { slug: "pizza", title: "Պիցցա", description: "Պիցցա" },
      en: { slug: "pizza", title: "Pizza", description: "Pizza" },
      ru: { slug: "pitstsa", title: "Пицца", description: "Пицца" },
    },
    productTitles: productTitles([
      { hy: "Մարգարիտա", en: "Margherita", ru: "Маргарита" },
      { hy: "Պեպպերոնի", en: "Pepperoni", ru: "Пепперони" },
      { hy: "Չորս պանիր", en: "Four cheese", ru: "Четыре сыра" },
      { hy: "Հավով պիցցա", en: "Chicken pizza", ru: "Пицца с курицей" },
      { hy: "Մսային", en: "Meat lovers", ru: "Мясная" },
      { hy: "Բանջարեղենային", en: "Veggie pizza", ru: "Овощная" },
      { hy: "Հավայան", en: "Hawaiian", ru: "Гавайская" },
      { hy: "Կապրիչոզա", en: "Capricciosa", ru: "Капричоза" },
      { hy: "Դիաբլո", en: "Diablo", ru: "Диабло" },
      { hy: "Սնկով", en: "Mushroom pizza", ru: "С грибами" },
      { hy: "Տոնո", en: "Tuna pizza", ru: "С тунцом" },
      { hy: "Բարբեքյու", en: "BBQ pizza", ru: "Барбекю" },
      { hy: "Պարմա", en: "Parma", ru: "Парма" },
      { hy: "Կալցոնե", en: "Calzone", ru: "Кальцоне" },
      { hy: "Դեգուստո ֆիրմային", en: "Degusto special", ru: "Фирменная Degusto" },
      { hy: "Մոցարելլա", en: "Mozzarella pizza", ru: "Моцарелла" },
      { hy: "Սալյամի", en: "Salami pizza", ru: "Салями" },
      { hy: "Մինի պիցցա", en: "Mini pizza", ru: "Мини пицца" },
    ]),
  },
  {
    key: "lahmajoun",
    sortOrder: 5,
    iconKey: "assets/categories/icons/lahmajoun.webp",
    translations: {
      hy: { slug: "lahmajoun", title: "Լահմաջո", description: "Լահմաջո" },
      en: { slug: "lahmajoun", title: "Lahmajoun", description: "Lahmajoun" },
      ru: { slug: "lakhmadzhun", title: "Лахмаджун", description: "Лахмаджун" },
    },
    productTitles: productTitles([
      { hy: "Դասական լահմաջո", en: "Classic lahmajoun", ru: "Классический лахмаджун" },
      { hy: "Կծու լահմաջո", en: "Spicy lahmajoun", ru: "Острый лахмаджун" },
      { hy: "Պանրով լահմաջո", en: "Cheese lahmajoun", ru: "Лахмаджун с сыром" },
      { hy: "Բանջարեղենային", en: "Veggie lahmajoun", ru: "Овощной лахмаджун" },
      { hy: "Մեծ լահմաջո", en: "Large lahmajoun", ru: "Большой лахмаджун" },
      { hy: "Փոքր լահմաջո", en: "Small lahmajoun", ru: "Маленький лахмаджун" },
      { hy: "Գառան լահմաջո", en: "Lamb lahmajoun", ru: "Бараний лахмаджун" },
      { hy: "Հավի լահմաջո", en: "Chicken lahmajoun", ru: "Куриный лахмаджун" },
      { hy: "Դաբլ լահմաջո", en: "Double lahmajoun", ru: "Двойной лахмаджун" },
      { hy: "Ֆիրմային", en: "Signature lahmajoun", ru: "Фирменный" },
      { hy: "Սոուսով", en: "With sauce", ru: "С соусом" },
      { hy: "Թարմ խոտաբույսերով", en: "With herbs", ru: "С зеленью" },
      { hy: "Լոլիկով", en: "With tomato", ru: "С томатом" },
      { hy: "Սոխով", en: "With onion", ru: "С луком" },
      { hy: "Խառը", en: "Mixed", ru: "Смешанный" },
      { hy: "Մինի լահմաջո", en: "Mini lahmajoun", ru: "Мини лахмаджун" },
      { hy: "Կոմպլեկտ 2 հատ", en: "Set of 2", ru: "Комплект 2 шт" },
      { hy: "Կոմպլեկտ 4 հատ", en: "Set of 4", ru: "Комплект 4 шт" },
    ]),
  },
  {
    key: "khachapuri",
    sortOrder: 6,
    iconKey: "assets/categories/icons/khachapuri.webp",
    translations: {
      hy: {
        slug: "khachapuri",
        title: "Վրացական Խաչապուրի",
        description: "Վրացական խաչապուրի",
      },
      en: {
        slug: "khachapuri",
        title: "Georgian Khachapuri",
        description: "Georgian khachapuri",
      },
      ru: {
        slug: "khachapuri",
        title: "Грузинский хачапури",
        description: "Грузинский хачапури",
      },
    },
    productTitles: productTitles([
      { hy: "Աջարական", en: "Adjarian", ru: "Аджарский" },
      { hy: "Իմերեթական", en: "Imeretian", ru: "Имеретинский" },
      { hy: "Մեգրելական", en: "Megrelian", ru: "Мегрельский" },
      { hy: "Պանրով", en: "Cheese khachapuri", ru: "С сыром" },
      { hy: "Սնկով", en: "Mushroom khachapuri", ru: "С грибами" },
      { hy: "Մսով", en: "Meat khachapuri", ru: "С мясом" },
      { hy: "Ձվով", en: "Egg khachapuri", ru: "С яйцом" },
      { hy: "Խառը", en: "Mixed khachapuri", ru: "Смешанный" },
      { hy: "Մեծ աջարական", en: "Large Adjarian", ru: "Большой аджарский" },
      { hy: "Փոքր աջարական", en: "Small Adjarian", ru: "Малый аджарский" },
      { hy: "Ֆիրմային", en: "Signature", ru: "Фирменный" },
      { hy: "Կծու", en: "Spicy", ru: "Острый" },
      { hy: "Կանաչիով", en: "With greens", ru: "С зеленью" },
      { hy: "Բեկոնով", en: "With bacon", ru: "С беконом" },
      { hy: "Երկտակ պանիր", en: "Double cheese", ru: "Двойной сыр" },
      { hy: "Մինի խաչապուրի", en: "Mini khachapuri", ru: "Мини хачапури" },
      { hy: "Լոբիանի", en: "Lobiani", ru: "Лобиани" },
      { hy: "Կուբդարի", en: "Kubdari", ru: "Кубдари" },
    ]),
  },
  {
    key: "khorovats",
    sortOrder: 7,
    iconKey: "assets/categories/icons/khorovats.webp",
    translations: {
      hy: { slug: "khorovats", title: "Խորոված", description: "Խորոված" },
      en: { slug: "khorovats", title: "Barbecue", description: "Barbecue" },
      ru: { slug: "khorovats", title: "Шашлык", description: "Шашлык" },
    },
    productTitles: productTitles([
      { hy: "Խոզի խորոված", en: "Pork khorovats", ru: "Свиной шашлык" },
      { hy: "Հավի խորոված", en: "Chicken khorovats", ru: "Куриный шашлык" },
      { hy: "Գառան խորոված", en: "Lamb khorovats", ru: "Бараний шашлык" },
      { hy: "Տավարի խորոված", en: "Beef khorovats", ru: "Говяжий шашлык" },
      { hy: "Լյարդի խորոված", en: "Liver khorovats", ru: "Шашлык из печени" },
      { hy: "Բանջարեղեն խորոված", en: "Veggie grill", ru: "Овощи на гриле" },
      { hy: "Խորոված պլատո", en: "Khorovats platter", ru: "Шашлык плато" },
      { hy: "Կողիկներ", en: "Ribs", ru: "Рёбра" },
      { hy: "Թևիկներ", en: "Wings", ru: "Крылышки" },
      { hy: "Քյաբաբ", en: "Kebab", ru: "Кебаб" },
      { hy: "Լուլա քյաբաբ", en: "Lula kebab", ru: "Люля-кебаб" },
      { hy: "Սաղմոն գրիլ", en: "Grilled salmon", ru: "Лосось гриль" },
      { hy: "Շամփուր հավ", en: "Chicken skewer", ru: "Курица на шампуре" },
      { hy: "Շամփուր միս", en: "Meat skewer", ru: "Мясо на шампуре" },
      { hy: "Խորոված կոմբո", en: "Grill combo", ru: "Гриль комбо" },
      { hy: "Կծու խորոված", en: "Spicy grill", ru: "Острый шашлык" },
      { hy: "Մարինադով", en: "Marinated grill", ru: "В маринаде" },
      { hy: "Ընտանեկան պլատո", en: "Family platter", ru: "Семейное плато" },
    ]),
  },
  {
    key: "khinkali",
    sortOrder: 8,
    iconKey: "assets/categories/icons/khinkali.webp",
    translations: {
      hy: { slug: "khinkali", title: "Խինկալի", description: "Խինկալի" },
      en: { slug: "khinkali", title: "Khinkali", description: "Khinkali" },
      ru: { slug: "khinkali", title: "Хинкали", description: "Хинкали" },
    },
    productTitles: productTitles([
      { hy: "Մսով խինկալի", en: "Meat khinkali", ru: "Хинкали с мясом" },
      { hy: "Պանրով խինկալի", en: "Cheese khinkali", ru: "Хинкали с сыром" },
      { hy: "Սնկով խինկալի", en: "Mushroom khinkali", ru: "Хинкали с грибами" },
      { hy: "Խառը խինկալի", en: "Mixed khinkali", ru: "Смешанные хинкали" },
      { hy: "Կծու խինկալի", en: "Spicy khinkali", ru: "Острые хинкали" },
      { hy: "Խինկալի 5 հատ", en: "Khinkali 5 pcs", ru: "Хинкали 5 шт" },
      { hy: "Խինկալի 10 հատ", en: "Khinkali 10 pcs", ru: "Хинкали 10 шт" },
      { hy: "Խինկալի 15 հատ", en: "Khinkali 15 pcs", ru: "Хинкали 15 шт" },
      { hy: "Գառան խինկալի", en: "Lamb khinkali", ru: "Хинкали с бараниной" },
      { hy: "Հավի խինկալի", en: "Chicken khinkali", ru: "Хинкали с курицей" },
      { hy: "Կանաչիով", en: "With herbs", ru: "С зеленью" },
      { hy: "Տապակած խինկալի", en: "Fried khinkali", ru: "Жареные хинкали" },
      { hy: "Խաշած խինկալի", en: "Boiled khinkali", ru: "Варёные хинкали" },
      { hy: "Ֆիրմային", en: "Signature", ru: "Фирменные" },
      { hy: "Մինի խինկալի", en: "Mini khinkali", ru: "Мини хинкали" },
      { hy: "Պլատո խինկալի", en: "Khinkali platter", ru: "Плато хинкали" },
      { hy: "Կարտոֆիլով", en: "Potato khinkali", ru: "С картофелем" },
      { hy: "Դդմով", en: "Pumpkin khinkali", ru: "С тыквой" },
    ]),
  },
  {
    key: "stuffed-potato",
    sortOrder: 9,
    iconKey: "assets/categories/icons/stuffed-potato.webp",
    translations: {
      hy: {
        slug: "ltsonats-kartofil",
        title: "Լցոնած կարտոֆիլ",
        description: "Լցոնած կարտոֆիլ",
      },
      en: {
        slug: "stuffed-potato",
        title: "Stuffed potato",
        description: "Stuffed potato",
      },
      ru: {
        slug: "farsirovannyj-kartofel",
        title: "Фаршированный картофель",
        description: "Фаршированный картофель",
      },
    },
    productTitles: productTitles([
      { hy: "Պանրով կարտոֆիլ", en: "Cheese potato", ru: "Картофель с сыром" },
      { hy: "Մսով կարտոֆիլ", en: "Meat potato", ru: "Картофель с мясом" },
      { hy: "Հավով կարտոֆիլ", en: "Chicken potato", ru: "Картофель с курицей" },
      { hy: "Սնկով կարտոֆիլ", en: "Mushroom potato", ru: "Картофель с грибами" },
      { hy: "Բեկոնով", en: "Bacon potato", ru: "С беконом" },
      { hy: "Բանջարեղենային", en: "Veggie potato", ru: "Овощной" },
      { hy: "Կծու", en: "Spicy potato", ru: "Острый" },
      { hy: "Ֆիրմային", en: "Signature potato", ru: "Фирменный" },
      { hy: "Թթվասերով", en: "With sour cream", ru: "Со сметаной" },
      { hy: "Խառը լցոնում", en: "Mixed stuffing", ru: "Смешанная начинка" },
      { hy: "Մեծ չափ", en: "Large size", ru: "Большой размер" },
      { hy: "Փոքր չափ", en: "Small size", ru: "Малый размер" },
      { hy: "Կրկնակի պանիր", en: "Double cheese", ru: "Двойной сыр" },
      { hy: "Գրիլ կարտոֆիլ", en: "Grill potato", ru: "Гриль картофель" },
      { hy: "Սոխով", en: "With onion", ru: "С луком" },
      { hy: "Խոտաբույսերով", en: "With herbs", ru: "С зеленью" },
      { hy: "Կոմբո 2 հատ", en: "Combo 2 pcs", ru: "Комбо 2 шт" },
      { hy: "Ընտանեկան", en: "Family portion", ru: "Семейная порция" },
    ]),
  },
  {
    key: "burgers-sandwiches",
    sortOrder: 10,
    iconKey: "assets/categories/icons/burgers-sandwiches.webp",
    translations: {
      hy: {
        slug: "burgerner-sendvichner",
        title: "Բուրգերներ եւ սենդվիչներ",
        description: "Բուրգերներ և սենդվիչներ",
      },
      en: {
        slug: "burgers-sandwiches",
        title: "Burgers & sandwiches",
        description: "Burgers and sandwiches",
      },
      ru: {
        slug: "burgery-sendvichi",
        title: "Бургеры и сэндвичи",
        description: "Бургеры и сэндвичи",
      },
    },
    productTitles: productTitles([
      { hy: "Դասական բուրգեր", en: "Classic burger", ru: "Классический бургер" },
      { hy: "Չիզբուրգեր", en: "Cheeseburger", ru: "Чизбургер" },
      { hy: "Դաբլ չիզ", en: "Double cheese", ru: "Двойной чиз" },
      { hy: "Կծու բուրգեր", en: "Spicy burger", ru: "Острый бургер" },
      { hy: "Հավի բուրգեր", en: "Chicken burger", ru: "Куриный бургер" },
      { hy: "Բեկոն բուրգեր", en: "Bacon burger", ru: "Бургер с беконом" },
      { hy: "Բանջարեղենային", en: "Veggie burger", ru: "Овощной бургер" },
      { hy: "Կլաբ սենդվիչ", en: "Club sandwich", ru: "Клаб сэндвич" },
      { hy: "Հավի սենդվիչ", en: "Chicken sandwich", ru: "Куриный сэндвич" },
      { hy: "Թունա սենդվիչ", en: "Tuna sandwich", ru: "Сэндвич с тунцом" },
      { hy: "Դելյուքս բուրգեր", en: "Deluxe burger", ru: "Делюкс бургер" },
      { hy: "Ֆիրմային բուրգեր", en: "Signature burger", ru: "Фирменный бургер" },
      { hy: "Սմուկի սենդվիչ", en: "Smoky sandwich", ru: "Копчёный сэндвич" },
      { hy: "Պանրով սենդվիչ", en: "Cheese sandwich", ru: "Сырный сэндвич" },
      { hy: "Գրիլ սենդվիչ", en: "Grill sandwich", ru: "Гриль сэндвич" },
      { hy: "Մինի բուրգեր", en: "Mini burger", ru: "Мини бургер" },
      { hy: "Բուրգեր մենյու", en: "Burger meal", ru: "Бургер меню" },
      { hy: "Հոթ դոգ", en: "Hot dog", ru: "Хот-дог" },
    ]),
  },
  {
    key: "cakes-pancakes",
    sortOrder: 11,
    iconKey: "assets/categories/icons/cakes-pancakes.webp",
    translations: {
      hy: {
        slug: "karkandakner-nrbaablitner",
        title: "Կարկանդակներ եւ նրբաբլիթներ",
        description: "Կարկանդակներ և նրբաբլիթներ",
      },
      en: {
        slug: "pies-pancakes",
        title: "Pies & pancakes",
        description: "Pies and pancakes",
      },
      ru: {
        slug: "pirozhki-bliny",
        title: "Пирожки и блины",
        description: "Пирожки и блины",
      },
    },
    productTitles: productTitles([
      { hy: "Մսով կարկանդակ", en: "Meat pie", ru: "Пирожок с мясом" },
      { hy: "Պանրով կարկանդակ", en: "Cheese pie", ru: "Пирожок с сыром" },
      { hy: "Կարտոֆիլով", en: "Potato pie", ru: "С картофелем" },
      { hy: "Կաղամբով", en: "Cabbage pie", ru: "С капустой" },
      { hy: "Սնկով", en: "Mushroom pie", ru: "С грибами" },
      { hy: "Քաղցր կարկանդակ", en: "Sweet pie", ru: "Сладкий пирожок" },
      { hy: "Նրբաբլիթ մսով", en: "Meat pancake", ru: "Блин с мясом" },
      { hy: "Նրբաբլիթ պանրով", en: "Cheese pancake", ru: "Блин с сыром" },
      { hy: "Նրբաբլիթ մեղրով", en: "Honey pancake", ru: "Блин с мёдом" },
      { hy: "Նրբաբլիթ մուրաբայով", en: "Jam pancake", ru: "Блин с вареньем" },
      { hy: "Պանրով բլինչիկ", en: "Cheese blinchik", ru: "Сырный блинчик" },
      { hy: "Խնձորով կարկանդակ", en: "Apple pie", ru: "Яблочный пирог" },
      { hy: "Բալով", en: "Cherry pie", ru: "Вишнёвый" },
      { hy: "Խառը կարկանդակներ", en: "Assorted pies", ru: "Ассорти пирожков" },
      { hy: "Ֆիրմային", en: "Signature", ru: "Фирменный" },
      { hy: "Մինի կարկանդակ", en: "Mini pie", ru: "Мини пирожок" },
      { hy: "Կրեպ սյուզետ", en: "Crepe Suzette", ru: "Креп Сюзетт" },
      { hy: "Նրբաբլիթներ 3 հատ", en: "Pancakes 3 pcs", ru: "Блины 3 шт" },
    ]),
  },
  {
    key: "combo-packages",
    sortOrder: 12,
    iconKey: "assets/categories/icons/combo-packages.webp",
    translations: {
      hy: {
        slug: "kombo-paketner",
        title: "Կոմբո փաթեթներ",
        description: "Կոմբո փաթեթներ",
      },
      en: {
        slug: "combo-packages",
        title: "Combo packages",
        description: "Combo packages",
      },
      ru: {
        slug: "kombo-pakety",
        title: "Комбо-пакеты",
        description: "Комбо-пакеты",
      },
    },
    productTitles: productTitles([
      { hy: "Կոմբո 1", en: "Combo 1", ru: "Комбо 1" },
      { hy: "Կոմբո 2", en: "Combo 2", ru: "Комбо 2" },
      { hy: "Կոմբո 3", en: "Combo 3", ru: "Комбо 3" },
      { hy: "Ընտանեկան կոմբո", en: "Family combo", ru: "Семейное комбо" },
      { hy: "Բուրգեր կոմբո", en: "Burger combo", ru: "Бургер комбо" },
      { hy: "Պիցցա կոմբո", en: "Pizza combo", ru: "Пицца комбо" },
      { hy: "Շաուրմա կոմբո", en: "Shawarma combo", ru: "Шаурма комбо" },
      { hy: "Խորոված կոմբո", en: "Grill combo", ru: "Шашлык комбо" },
      { hy: "Լանչ կոմբո", en: "Lunch combo", ru: "Ланч комбо" },
      { hy: "Երեկոյան կոմբո", en: "Evening combo", ru: "Вечернее комбо" },
      { hy: "Երկուսի համար", en: "For two", ru: "На двоих" },
      { hy: "Չորսի համար", en: "For four", ru: "На четверых" },
      { hy: "Մանկական կոմբո", en: "Kids combo", ru: "Детское комбо" },
      { hy: "Ֆիրմային կոմբո", en: "Signature combo", ru: "Фирменное комбо" },
      { hy: "Խնայող կոմբո", en: "Value combo", ru: "Выгодное комбо" },
      { hy: "Պրեմիում կոմբո", en: "Premium combo", ru: "Премиум комбо" },
      { hy: "Խինկալի կոմբո", en: "Khinkali combo", ru: "Хинкали комбо" },
      { hy: "Սուշի կոմբո", en: "Sushi combo", ru: "Суши комбо" },
    ]),
  },
  {
    key: "lunch-boxes",
    sortOrder: 13,
    iconKey: "assets/categories/icons/lunch-boxes.webp",
    translations: {
      hy: {
        slug: "lunch-boxer",
        title: "Լանչ Բոքսեր",
        description: "Լանչ բոքսեր",
      },
      en: {
        slug: "lunch-boxes",
        title: "Lunch boxes",
        description: "Lunch boxes",
      },
      ru: {
        slug: "lanch-boksy",
        title: "Ланч-боксы",
        description: "Ланч-боксы",
      },
    },
    productTitles: productTitles([
      { hy: "Լանչ բոքս A", en: "Lunch box A", ru: "Ланч-бокс A" },
      { hy: "Լանչ բոքս B", en: "Lunch box B", ru: "Ланч-бокс B" },
      { hy: "Լանչ բոքս C", en: "Lunch box C", ru: "Ланч-бокс C" },
      { hy: "Հավով լանչ", en: "Chicken lunch", ru: "Куриный ланч" },
      { hy: "Մսով լանչ", en: "Meat lunch", ru: "Мясной ланч" },
      { hy: "Ձկան լանչ", en: "Fish lunch", ru: "Рыбный ланч" },
      { hy: "Բանջարեղենային", en: "Veggie lunch", ru: "Овощной ланч" },
      { hy: "Պահքի լանչ", en: "Lenten lunch", ru: "Постный ланч" },
      { hy: "Բիզնես լանչ", en: "Business lunch", ru: "Бизнес-ланч" },
      { hy: "Թեթև լանչ", en: "Light lunch", ru: "Лёгкий ланч" },
      { hy: "Կծու լանչ", en: "Spicy lunch", ru: "Острый ланч" },
      { hy: "Պաստա լանչ", en: "Pasta lunch", ru: "Ланч с пастой" },
      { hy: "Պլով լանչ", en: "Pilaf lunch", ru: "Ланч с пловом" },
      { hy: "Սալաթ + տաք", en: "Salad + hot", ru: "Салат + горячее" },
      { hy: "Ֆիրմային լանչ", en: "Signature lunch", ru: "Фирменный ланч" },
      { hy: "Մեծ լանչ", en: "Large lunch", ru: "Большой ланч" },
      { hy: "Փոքր լանչ", en: "Small lunch", ru: "Малый ланч" },
      { hy: "Օրվա լանչ", en: "Daily lunch", ru: "Ланч дня" },
    ]),
  },
  {
    key: "grill-smoked",
    sortOrder: 14,
    iconKey: "assets/categories/icons/grill-smoked.webp",
    translations: {
      hy: {
        slug: "gril-apxtats",
        title: "Գրիլ եւ ապխտած արտադրանքներ",
        description: "Գրիլ և ապխտած արտադրանքներ",
      },
      en: {
        slug: "grill-smoked",
        title: "Grill & smoked",
        description: "Grill and smoked products",
      },
      ru: {
        slug: "gril-kopchenoe",
        title: "Гриль и копчёности",
        description: "Гриль и копчёные продукты",
      },
    },
    productTitles: productTitles([
      { hy: "Ապխտած հավ", en: "Smoked chicken", ru: "Копчёная курица" },
      { hy: "Ապխտած միս", en: "Smoked meat", ru: "Копчёное мясо" },
      { hy: "Ապխտած նրբերշիկ", en: "Smoked sausage", ru: "Копчёная колбаса" },
      { hy: "Գրիլ կողիկներ", en: "Grill ribs", ru: "Рёбра гриль" },
      { hy: "Գրիլ կրծքամիս", en: "Grill breast", ru: "Грудка гриль" },
      { hy: "Ապխտած ձուկ", en: "Smoked fish", ru: "Копчёная рыба" },
      { hy: "Գրիլ բանջարեղեն", en: "Grill vegetables", ru: "Овощи гриль" },
      { hy: "Ապխտած պանիր", en: "Smoked cheese", ru: "Копчёный сыр" },
      { hy: "Գրիլ թևիկներ", en: "Grill wings", ru: "Крылышки гриль" },
      { hy: "Սմոուկի պլատո", en: "Smoky platter", ru: "Копчёное плато" },
      { hy: "Բեկոն ապխտած", en: "Smoked bacon", ru: "Копчёный бекон" },
      { hy: "Գրիլ սթեյք", en: "Grill steak", ru: "Стейк гриль" },
      { hy: "Ապխտած կողիկներ", en: "Smoked ribs", ru: "Копчёные рёбра" },
      { hy: "Ֆիրմային գրիլ", en: "Signature grill", ru: "Фирменный гриль" },
      { hy: "Խառը ապխտած", en: "Mixed smoked", ru: "Смешанное копчёное" },
      { hy: "Գրիլ նրբերշիկ", en: "Grill sausage", ru: "Колбаски гриль" },
      { hy: "Ապխտած հնդկահավ", en: "Smoked turkey", ru: "Копчёная индейка" },
      { hy: "Գրիլ պլատո", en: "Grill platter", ru: "Гриль плато" },
    ]),
  },
  {
    key: "bread",
    sortOrder: 15,
    iconKey: "assets/categories/icons/bread.webp",
    translations: {
      hy: { slug: "hats", title: "Հաց", description: "Հաց" },
      en: { slug: "bread", title: "Bread", description: "Bread" },
      ru: { slug: "khleb", title: "Хлеб", description: "Хлеб" },
    },
    productTitles: productTitles([
      { hy: "Լավաշ", en: "Lavash", ru: "Лаваш" },
      { hy: "Մատնաքաշ", en: "Matnakash", ru: "Матнакаш" },
      { hy: "Սև հաց", en: "Black bread", ru: "Чёрный хлеб" },
      { hy: "Սպիտակ հաց", en: "White bread", ru: "Белый хлеб" },
      { hy: "Հացիկ", en: "Bread roll", ru: "Булочка" },
      { hy: "Բագետ", en: "Baguette", ru: "Багет" },
      { hy: "Պիտա", en: "Pita", ru: "Пита" },
      { hy: "Թթխմորով հաց", en: "Sourdough", ru: "На закваске" },
      { hy: "Հաց ըստ պատվերի", en: "Custom bread", ru: "Хлеб на заказ" },
      { hy: "Սխտորով հաց", en: "Garlic bread", ru: "Чесночный хлеб" },
      { hy: "Պանրով հաց", en: "Cheese bread", ru: "Сырный хлеб" },
      { hy: "Ամբողջահատիկ", en: "Whole grain", ru: "Цельнозерновой" },
      { hy: "Տոստ հաց", en: "Toast bread", ru: "Тостовый хлеб" },
      { hy: "Բուրգերի բուլկի", en: "Burger buns", ru: "Булочки для бургера" },
      { hy: "Ֆոկաչա", en: "Focaccia", ru: "Фокачча" },
      { hy: "Չիաբաթա", en: "Ciabatta", ru: "Чиабатта" },
      { hy: "Լավաշ մեծ", en: "Large lavash", ru: "Большой лаваш" },
      { hy: "Լավաշ փոքր", en: "Small lavash", ru: "Малый лаваш" },
    ]),
  },
  {
    key: "pastry",
    sortOrder: 16,
    iconKey: "assets/categories/icons/pastry.webp",
    translations: {
      hy: { slug: "khmoreghen", title: "Խմորեղեն", description: "Խմորեղեն" },
      en: { slug: "pastry", title: "Pastry", description: "Pastry" },
      ru: { slug: "vypechka", title: "Выпечка", description: "Выпечка" },
    },
    productTitles: productTitles([
      { hy: "Կրուասան", en: "Croissant", ru: "Круассан" },
      { hy: "Պանրով կրուասան", en: "Cheese croissant", ru: "Круассан с сыром" },
      { hy: "Շոկոլադե կրուասան", en: "Chocolate croissant", ru: "Шоколадный круассан" },
      { hy: "Բուլկի", en: "Bun", ru: "Булочка" },
      { hy: "Քաղցր բուլկի", en: "Sweet bun", ru: "Сладкая булочка" },
      { hy: "Գաթա", en: "Gata", ru: "Гата" },
      { hy: "Փախլավա", en: "Pakhlava", ru: "Пахлава" },
      { hy: "Նազուք", en: "Nazook", ru: "Назук" },
      { hy: "Թխվածքաբլիթ", en: "Cookie", ru: "Печенье" },
      { hy: "Մաֆին", en: "Muffin", ru: "Маффин" },
      { hy: "Դոնաթ", en: "Donut", ru: "Пончик" },
      { hy: "Էկլեր", en: "Eclair", ru: "Эклер" },
      { hy: "Պրոֆիտրոլ", en: "Profiterole", ru: "Профитроль" },
      { hy: "Տարտ", en: "Tart", ru: "Тарт" },
      { hy: "Շտրուդել", en: "Strudel", ru: "Штрудель" },
      { hy: "Կարմրահայկական", en: "Armenian sweet", ru: "Армянская сладость" },
      { hy: "Ֆիրմային խմորեղեն", en: "Signature pastry", ru: "Фирменная выпечка" },
      { hy: "Ասորտի խմորեղեն", en: "Pastry assortment", ru: "Ассорти выпечки" },
    ]),
  },
  {
    key: "fried-eggs",
    sortOrder: 17,
    iconKey: "assets/categories/icons/fried-eggs.webp",
    translations: {
      hy: { slug: "dzvategh", title: "Ձվածեղ", description: "Ձվածեղ" },
      en: { slug: "omelette", title: "Omelette", description: "Omelette" },
      ru: { slug: "omlet", title: "Омлет", description: "Омлет" },
    },
    productTitles: productTitles([
      { hy: "Դասական ձվածեղ", en: "Classic omelette", ru: "Классический омлет" },
      { hy: "Պանրով ձվածեղ", en: "Cheese omelette", ru: "Омлет с сыром" },
      { hy: "Խոզապուխտով", en: "Ham omelette", ru: "Омлет с ветчиной" },
      { hy: "Սնկով ձվածեղ", en: "Mushroom omelette", ru: "Омлет с грибами" },
      { hy: "Բանջարեղենային", en: "Veggie omelette", ru: "Овощной омлет" },
      { hy: "Կծու ձվածեղ", en: "Spicy omelette", ru: "Острый омлет" },
      { hy: "Խառը ձվածեղ", en: "Mixed omelette", ru: "Смешанный омлет" },
      { hy: "Ձու աչքով", en: "Fried eggs", ru: "Яичница" },
      { hy: "Շաքշուկա", en: "Shakshuka", ru: "Шакшука" },
      { hy: "Բեկոնով ձու", en: "Eggs with bacon", ru: "Яйца с беконом" },
      { hy: "Թուրքական ձվածեղ", en: "Turkish omelette", ru: "Турецкий омлет" },
      { hy: "Ֆիրմային", en: "Signature omelette", ru: "Фирменный омлет" },
      { hy: "Լոլիկով", en: "Tomato omelette", ru: "С томатами" },
      { hy: "Սպանախով", en: "Spinach omelette", ru: "Со шпинатом" },
      { hy: "Երեք ձու", en: "Three eggs", ru: "Три яйца" },
      { hy: "Երկու ձու", en: "Two eggs", ru: "Два яйца" },
      { hy: "Նրբերշիկով", en: "With sausage", ru: "С колбасой" },
      { hy: "Կանաչիով", en: "With greens", ru: "С зеленью" },
    ]),
  },
  {
    key: "lenten-dishes",
    sortOrder: 18,
    iconKey: "assets/categories/icons/lenten-dishes.webp",
    translations: {
      hy: {
        slug: "pahqi-uteshtner",
        title: "Պահքի ուտեստներ",
        description: "Պահքի ուտեստներ",
      },
      en: {
        slug: "lenten-dishes",
        title: "Lenten dishes",
        description: "Lenten dishes",
      },
      ru: {
        slug: "postnye-blyuda",
        title: "Постные блюда",
        description: "Постные блюда",
      },
    },
    productTitles: productTitles([
      { hy: "Պահքի տոլմա", en: "Lenten tolma", ru: "Постная толма" },
      { hy: "Պահքի աղցան", en: "Lenten salad", ru: "Постный салат" },
      { hy: "Ոսպով ուտեստ", en: "Lentil dish", ru: "Блюдо из чечевицы" },
      { hy: "Բակլայով", en: "Bean dish", ru: "Блюдо из фасоли" },
      { hy: "Բանջարեղենային ռագու", en: "Veggie stew", ru: "Овощное рагу" },
      { hy: "Պահքի ապուր", en: "Lenten soup", ru: "Постный суп" },
      { hy: "Սնկով ուտեստ", en: "Mushroom dish", ru: "Грибное блюдо" },
      { hy: "Խաշած բանջարեղեն", en: "Boiled vegetables", ru: "Варёные овощи" },
      { hy: "Պահքի պլով", en: "Lenten pilaf", ru: "Постный плов" },
      { hy: "Պահքի պաստա", en: "Lenten pasta", ru: "Постная паста" },
      { hy: "Ավոկադո բոուլ", en: "Avocado bowl", ru: "Боул с авокадо" },
      { hy: "Քինոա բոուլ", en: "Quinoa bowl", ru: "Боул с киноа" },
      { hy: "Պահքի ֆալաֆել", en: "Lenten falafel", ru: "Постный фалафель" },
      { hy: "Հումուս պլատո", en: "Hummus platter", ru: "Плато хумуса" },
      { hy: "Պահքի կոմբո", en: "Lenten combo", ru: "Постное комбо" },
      { hy: "Ֆիրմային պահք", en: "Signature lenten", ru: "Фирменное постное" },
      { hy: "Թարմ հյութ + աղցան", en: "Juice + salad", ru: "Сок + салат" },
      { hy: "Պահքի լանչ", en: "Lenten lunch", ru: "Постный ланч" },
    ]),
  },
  {
    key: "asian-sushi",
    sortOrder: 19,
    iconKey: "assets/categories/icons/asian-sushi.webp",
    translations: {
      hy: {
        slug: "asiakan-sushi",
        title: "Ասիական խոհանոց (Սուշի)",
        description: "Ասիական խոհանոց և սուշի",
      },
      en: {
        slug: "asian-sushi",
        title: "Asian cuisine (Sushi)",
        description: "Asian cuisine and sushi",
      },
      ru: {
        slug: "aziatskaya-sushi",
        title: "Азиатская кухня (Суши)",
        description: "Азиатская кухня и суши",
      },
    },
    productTitles: productTitles([
      { hy: "Ֆիլադելֆիա", en: "Philadelphia", ru: "Филадельфия" },
      { hy: "Կալիֆորնիա", en: "California", ru: "Калифорния" },
      { hy: "Դրակոն", en: "Dragon roll", ru: "Дракон" },
      { hy: "Սաղմոն ռոլլ", en: "Salmon roll", ru: "Ролл с лососем" },
      { hy: "Ունագի", en: "Unagi", ru: "Унаги" },
      { hy: "Տեմպուրա ռոլլ", en: "Tempura roll", ru: "Темпура ролл" },
      { hy: "Բանջարեղենային ռոլլ", en: "Veggie roll", ru: "Овощной ролл" },
      { hy: "Սետ 24 հատ", en: "Set 24 pcs", ru: "Сет 24 шт" },
      { hy: "Սետ 36 հատ", en: "Set 36 pcs", ru: "Сет 36 шт" },
      { hy: "Նիգիրի սաղմոն", en: "Salmon nigiri", ru: "Нигири лосось" },
      { hy: "Սաշիմի", en: "Sashimi", ru: "Сашими" },
      { hy: "Վոկ հավով", en: "Chicken wok", ru: "Вок с курицей" },
      { hy: "Վոկ բանջարեղեն", en: "Veggie wok", ru: "Вок с овощами" },
      { hy: "Ռամեն", en: "Ramen", ru: "Рамен" },
      { hy: "Պադ թայ", en: "Pad Thai", ru: "Пад Тай" },
      { hy: "Գյոզա", en: "Gyoza", ru: "Гёдза" },
      { hy: "Էդամամե", en: "Edamame", ru: "Эдамаме" },
      { hy: "Միսո ապուր", en: "Miso soup", ru: "Мисо суп" },
    ]),
  },
  {
    key: "pasta",
    sortOrder: 20,
    iconKey: "assets/categories/icons/pasta.webp",
    translations: {
      hy: { slug: "pastaner", title: "Պաստաներ", description: "Պաստաներ" },
      en: { slug: "pasta", title: "Pasta", description: "Pasta" },
      ru: { slug: "pasta", title: "Паста", description: "Паста" },
    },
    productTitles: productTitles([
      { hy: "Կարբոնարա", en: "Carbonara", ru: "Карбонара" },
      { hy: "Բոլոնեզ", en: "Bolognese", ru: "Болоньезе" },
      { hy: "Ալֆրեդո", en: "Alfredo", ru: "Альфредо" },
      { hy: "Արաբիաթա", en: "Arrabbiata", ru: "Араббиата" },
      { hy: "Պեստո", en: "Pesto pasta", ru: "Паста песто" },
      { hy: "Ծովամթերք պաստա", en: "Seafood pasta", ru: "Паста с морепродуктами" },
      { hy: "Հավով պաստա", en: "Chicken pasta", ru: "Паста с курицей" },
      { hy: "Սնկով պաստա", en: "Mushroom pasta", ru: "Паста с грибами" },
      { hy: "Լազանիա", en: "Lasagna", ru: "Лазанья" },
      { hy: "Ռավիոլի", en: "Ravioli", ru: "Равиоли" },
      { hy: "Սպագետտի", en: "Spaghetti", ru: "Спагетти" },
      { hy: "Պեննե", en: "Penne", ru: "Пенне" },
      { hy: "Ֆետուչինի", en: "Fettuccine", ru: "Феттучини" },
      { hy: "Տորտելինի", en: "Tortellini", ru: "Тортеллини" },
      { hy: "Չորս պանիր պաստա", en: "Four cheese pasta", ru: "Паста четыре сыра" },
      { hy: "Բանջարեղենային", en: "Veggie pasta", ru: "Овощная паста" },
      { hy: "Ֆիրմային պաստա", en: "Signature pasta", ru: "Фирменная паста" },
      { hy: "Մակարոններ պանրով", en: "Mac & cheese", ru: "Мак энд чиз" },
    ]),
  },
  {
    key: "sauces",
    sortOrder: 21,
    iconKey: "assets/categories/icons/sauces.webp",
    translations: {
      hy: { slug: "sousner", title: "Սոուսներ", description: "Սոուսներ" },
      en: { slug: "sauces", title: "Sauces", description: "Sauces" },
      ru: { slug: "sousy", title: "Соусы", description: "Соусы" },
    },
    productTitles: productTitles([
      { hy: "Կետչուպ", en: "Ketchup", ru: "Кетчуп" },
      { hy: "Մայոնեզ", en: "Mayonnaise", ru: "Майонез" },
      { hy: "Սխտորի սոուս", en: "Garlic sauce", ru: "Чесночный соус" },
      { hy: "Կծու սոուս", en: "Hot sauce", ru: "Острый соус" },
      { hy: "Բարբեքյու սոուս", en: "BBQ sauce", ru: "Соус барбекю" },
      { hy: "Պանրի սոուս", en: "Cheese sauce", ru: "Сырный соус" },
      { hy: "Թաթարական", en: "Tartar sauce", ru: "Тартар" },
      { hy: "Սոևի սոուս", en: "Soy sauce", ru: "Соевый соус" },
      { hy: "Քաղցր չիլի", en: "Sweet chili", ru: "Сладкий чили" },
      { hy: "Մանանեխ", en: "Mustard", ru: "Горчица" },
      { hy: "Հումուս", en: "Hummus", ru: "Хумус" },
      { hy: "Թխված սոուս", en: "Tzatziki", ru: "Дзадзики" },
      { hy: "Նարշարաբ", en: "Narsharab", ru: "Наршараб" },
      { hy: "Աջիկա", en: "Adjika", ru: "Аджика" },
      { hy: "Թխվածքաբլիթի սոուս", en: "Dip sauce", ru: "Соус для дипа" },
      { hy: "Ֆիրմային սոուս", en: "Signature sauce", ru: "Фирменный соус" },
      { hy: "Սերուցքային", en: "Cream sauce", ru: "Сливочный соус" },
      { hy: "Լոլիկի սոուս", en: "Tomato sauce", ru: "Томатный соус" },
    ]),
  },
  {
    key: "restaurant",
    sortOrder: 22,
    iconKey: "assets/categories/icons/restaurant.webp",
    translations: {
      hy: { slug: "restoran", title: "Ռեստորան", description: "Ռեստորանային ուտեստներ" },
      en: { slug: "restaurant", title: "Restaurant", description: "Restaurant dishes" },
      ru: { slug: "restoran", title: "Ресторан", description: "Ресторанные блюда" },
    },
    productTitles: productTitles([
      { hy: "Սթեյք միջին", en: "Medium steak", ru: "Стейк средний" },
      { hy: "Սաղմոն սթեյք", en: "Salmon steak", ru: "Стейк из лосося" },
      { hy: "Ռիզոտո", en: "Risotto", ru: "Ризотто" },
      { hy: "Դաքս կոնֆի", en: "Duck confit", ru: "Утка конфи" },
      { hy: "Գառան ոտք", en: "Lamb shank", ru: "Голень ягнёнка" },
      { hy: "Ծովախեցգետին", en: "Shrimp plate", ru: "Креветки" },
      { hy: "Միդիաներ", en: "Mussels", ru: "Мидии" },
      { hy: "Պրեմիում աղցան", en: "Premium salad", ru: "Премиум салат" },
      { hy: "Շեֆի ուտեստ", en: "Chef special", ru: "Блюдо шефа" },
      { hy: "Տավարի ֆիլե", en: "Beef fillet", ru: "Филе говядины" },
      { hy: "Հավի կրծքամիս գրիլ", en: "Grill chicken breast", ru: "Куриная грудка гриль" },
      { hy: "Բանջարեղենային գլխավոր", en: "Veggie main", ru: "Овощное основное" },
      { hy: "Սոբա լապշա", en: "Soba noodles", ru: "Соба" },
      { hy: "Պոլենտա", en: "Polenta", ru: "Полента" },
      { hy: "Ֆուա գրա", en: "Foie gras", ru: "Фуа-гра" },
      { hy: "Կարիճ ծովախեցգետին", en: "King prawns", ru: "Королевские креветки" },
      { hy: "Ռեստորանային պլատո", en: "Restaurant platter", ru: "Ресторанное плато" },
      { hy: "Դեգուստացիոն սեթ", en: "Tasting set", ru: "Дегустационный сет" },
    ]),
  },
  {
    key: "bar-alcohol",
    sortOrder: 23,
    iconKey: "assets/categories/icons/bar-alcohol.webp",
    translations: {
      hy: {
        slug: "bar-alkohol",
        title: "Բար (Ալկոհոլ)",
        description: "Բար և ալկոհոլ",
      },
      en: {
        slug: "bar-alcohol",
        title: "Bar (Alcohol)",
        description: "Bar and alcohol",
      },
      ru: {
        slug: "bar-alkogol",
        title: "Бар (Алкоголь)",
        description: "Бар и алкоголь",
      },
    },
    productTitles: productTitles([
      { hy: "Կարմիր գինի", en: "Red wine", ru: "Красное вино" },
      { hy: "Սպիտակ գինի", en: "White wine", ru: "Белое вино" },
      { hy: "Շամպայն", en: "Champagne", ru: "Шампанское" },
      { hy: "Գարեջուր", en: "Beer", ru: "Пиво" },
      { hy: "Օղի", en: "Vodka", ru: "Водка" },
      { hy: "Վիսկի", en: "Whiskey", ru: "Виски" },
      { hy: "Կոնյակ", en: "Cognac", ru: "Коньяк" },
      { hy: "Ռոմ", en: "Rum", ru: "Ром" },
      { hy: "Ջին", en: "Gin", ru: "Джин" },
      { hy: "Թեքիլա", en: "Tequila", ru: "Текила" },
      { hy: "Մոխիտո", en: "Mojito", ru: "Мохито" },
      { hy: "Մարգարիտա կոկտեյլ", en: "Margarita cocktail", ru: "Маргарита" },
      { hy: "Ապերոլ շպրից", en: "Aperol spritz", ru: "Апероль шприц" },
      { hy: "Բլոդի Մերի", en: "Bloody Mary", ru: "Кровавая Мэри" },
      { hy: "Վիսկի սաուր", en: "Whiskey sour", ru: "Виски сауэр" },
      { hy: "Լոկալ գինի", en: "Local wine", ru: "Местное вино" },
      { hy: "Ոչալկոհոլային կոկտեյլ", en: "Mocktail", ru: "Безалкогольный коктейль" },
      { hy: "Բար սնեք սեթ", en: "Bar snack set", ru: "Барный снек-сет" },
    ]),
  },
  {
    key: "juices-drinks",
    sortOrder: 24,
    iconKey: "assets/categories/icons/juices-drinks.webp",
    translations: {
      hy: {
        slug: "hyuter-ympelikner",
        title: "Հյութեր և Ըմպելիքներ",
        description: "Հյութեր և ըմպելիքներ",
      },
      en: {
        slug: "juices-drinks",
        title: "Juices & drinks",
        description: "Juices and drinks",
      },
      ru: {
        slug: "soki-napitki",
        title: "Соки и напитки",
        description: "Соки и напитки",
      },
    },
    productTitles: productTitles([
      { hy: "Նարնջի հյութ", en: "Orange juice", ru: "Апельсиновый сок" },
      { hy: "Խնձորի հյութ", en: "Apple juice", ru: "Яблочный сок" },
      { hy: "Լիմոնադ", en: "Lemonade", ru: "Лимонад" },
      { hy: "Թարմ թեյ", en: "Fresh tea", ru: "Свежий чай" },
      { hy: "Սուրճ", en: "Coffee", ru: "Кофе" },
      { hy: "Կապուչինո", en: "Cappuccino", ru: "Капучино" },
      { hy: "Ամերիկանո", en: "Americano", ru: "Американо" },
      { hy: "Լատտե", en: "Latte", ru: "Латте" },
      { hy: "Կոկա-կոլա", en: "Cola", ru: "Кола" },
      { hy: "Հանքային ջուր", en: "Mineral water", ru: "Минеральная вода" },
      { hy: "Սմուզի", en: "Smoothie", ru: "Смузи" },
      { hy: "Կաթնաշոռ ըմպելիք", en: "Ayran", ru: "Айран" },
      { hy: "Թան", en: "Tan", ru: "Тан" },
      { hy: "Կոմպոտ", en: "Kompot", ru: "Компот" },
      { hy: "Նռան հյութ", en: "Pomegranate juice", ru: "Гранатовый сок" },
      { hy: "Սառը սուրճ", en: "Iced coffee", ru: "Холодный кофе" },
      { hy: "Մոջիտո զրո", en: "Virgin mojito", ru: "Мохито без алкоголя" },
      { hy: "Թարմ միլքշեյք", en: "Milkshake", ru: "Молочный коктейль" },
    ]),
  },
  {
    key: "semi-finished",
    sortOrder: 25,
    iconKey: "assets/categories/icons/semi-finished.webp",
    translations: {
      hy: {
        slug: "kisafabrikatner",
        title: "Կիսաֆաբրիկատներ",
        description: "Կիսաֆաբրիկատներ",
      },
      en: {
        slug: "semi-finished",
        title: "Semi-finished",
        description: "Semi-finished products",
      },
      ru: {
        slug: "polufabrikaty",
        title: "Полуфабрикаты",
        description: "Полуфабрикаты",
      },
    },
    productTitles: productTitles([
      { hy: "Սառեցված խինկալի", en: "Frozen khinkali", ru: "Хинкали замороженные" },
      { hy: "Սառեցված տոլմա", en: "Frozen tolma", ru: "Толма замороженная" },
      { hy: "Կոտլետներ", en: "Cutlets", ru: "Котлеты" },
      { hy: "Նրբերշիկներ", en: "Sausages", ru: "Колбаски" },
      { hy: "Խմոր կիսաֆաբրիկատ", en: "Dough semi-finished", ru: "Тесто полуфабрикат" },
      { hy: "Պելմենի", en: "Pelmeni", ru: "Пельмени" },
      { hy: "Վարենիկի", en: "Vareniki", ru: "Вареники" },
      { hy: "Պիցցայի հիմք", en: "Pizza base", ru: "Основа для пиццы" },
      { hy: "Լահմաջո սառեցված", en: "Frozen lahmajoun", ru: "Лахмаджун замороженный" },
      { hy: "Խաչապուրի սառեցված", en: "Frozen khachapuri", ru: "Хачапури замороженный" },
      { hy: "Մսային գնդիկներ", en: "Meatballs", ru: "Фрикадельки" },
      { hy: "Հավի նագեթներ", en: "Chicken nuggets", ru: "Наггетсы" },
      { hy: "Ֆրի կիսաֆաբրիկատ", en: "Frozen fries", ru: "Картофель фри" },
      { hy: "Բլինչիկներ սառեցված", en: "Frozen blinchiki", ru: "Блинчики замороженные" },
      { hy: "Կարկանդակ սառեցված", en: "Frozen pie", ru: "Пирожок замороженный" },
      { hy: "Խառը փաթեթ", en: "Mixed pack", ru: "Смешанный пакет" },
      { hy: "Ընտանեկան փաթեթ", en: "Family pack", ru: "Семейный пакет" },
      { hy: "Ֆիրմային կիսաֆաբրիկատ", en: "Signature pack", ru: "Фирменный набор" },
    ]),
  },
  {
    key: "mexican",
    sortOrder: 26,
    iconKey: "assets/categories/icons/mexican.webp",
    translations: {
      hy: {
        slug: "mexikakan",
        title: "Մեքսիկական խոհանոց",
        description: "Մեքսիկական խոհանոց",
      },
      en: {
        slug: "mexican",
        title: "Mexican cuisine",
        description: "Mexican cuisine",
      },
      ru: {
        slug: "meksikanskaya",
        title: "Мексиканская кухня",
        description: "Мексиканская кухня",
      },
    },
    productTitles: productTitles([
      { hy: "Տակո հավով", en: "Chicken taco", ru: "Тако с курицей" },
      { hy: "Տակո տավարով", en: "Beef taco", ru: "Тако с говядиной" },
      { hy: "Բուրիտո", en: "Burrito", ru: "Буррито" },
      { hy: "Քեսադիլլա", en: "Quesadilla", ru: "Кесадилья" },
      { hy: "Նաչոս", en: "Nachos", ru: "Начос" },
      { hy: "Գուակամոլե", en: "Guacamole", ru: "Гуакамоле" },
      { hy: "Էնչիլադա", en: "Enchilada", ru: "Энчилада" },
      { hy: "Ֆախիտա", en: "Fajita", ru: "Фахита" },
      { hy: "Տակո բանջարեղեն", en: "Veggie taco", ru: "Овощное тако" },
      { hy: "Կծու բուրիտո", en: "Spicy burrito", ru: "Острый буррито" },
      { hy: "Չիլի կոն կարնե", en: "Chili con carne", ru: "Чили кон карне" },
      { hy: "Մեքսիկական աղցան", en: "Mexican salad", ru: "Мексиканский салат" },
      { hy: "Սալսա սեթ", en: "Salsa set", ru: "Набор сальсы" },
      { hy: "Տակո պլատո", en: "Taco platter", ru: "Плато тако" },
      { hy: "Քեսադիլլա պանրով", en: "Cheese quesadilla", ru: "Кесадилья с сыром" },
      { hy: "Նաչոս պանրով", en: "Cheese nachos", ru: "Начос с сыром" },
      { hy: "Ֆիրմային մեքսիկական", en: "Signature Mexican", ru: "Фирменное мексиканское" },
      { hy: "Մեքսիկական կոմբո", en: "Mexican combo", ru: "Мексиканское комбо" },
    ]),
  },
];
