'use client';

import { useEffect } from 'react';
import {
  recomputeVariantPriceWithAdjustments,
  sumAttributeValuePriceAdjustments,
} from '@/lib/attributes/price-adjustment';
import type { Attribute, GeneratedVariant } from '../types';
import { generateSkuFromSlug, slugifyProductTitle } from '../utils/productUtils';
import { logger } from "@/lib/utils/logger";

interface UseVariantGenerationProps {
  selectedAttributesForVariants: Set<string>;
  selectedAttributeValueIds: Record<string, string[]>;
  attributes: Attribute[];
  generatedVariants: GeneratedVariant[];
  formDataSlug: string;
  formDataTitle: string;
  isEditMode: boolean;
  productId: string | null;
  /** True while edit-mode product variants are waiting to be converted from window payload. */
  hasVariantsToLoad: boolean;
  setGeneratedVariants: (updater: (prev: GeneratedVariant[]) => GeneratedVariant[]) => void;
}

export function useVariantGeneration({
  selectedAttributesForVariants,
  selectedAttributeValueIds,
  attributes,
  generatedVariants,
  formDataSlug,
  formDataTitle,
  isEditMode,
  productId,
  hasVariantsToLoad,
  setGeneratedVariants,
}: UseVariantGenerationProps) {
  const generateVariantsFromAttributes = () => {
    logger.debug('🚀 [VARIANT BUILDER] Generating single variant with all attributes...');

    const selectedAttrs = Array.from(selectedAttributesForVariants);
    if (selectedAttrs.length === 0) {
      logger.debug('⚠️ [VARIANT BUILDER] No attributes selected');
      setGeneratedVariants(() => []);
      return;
    }

    setGeneratedVariants((prev) => {
      const manuallyAddedVariants = prev.filter((v) => v.id !== 'variant-all');
      const existingAutoVariant = prev.find((v) => v.id === 'variant-all');

      if (manuallyAddedVariants.length > 0) {
        logger.debug('✅ [VARIANT BUILDER] Manual variants exist, skipping auto-generated variant');
        return manuallyAddedVariants;
      }

      const variantId = 'variant-all';
      const allSelectedValueIds: string[] = [];
      selectedAttrs.forEach((attributeId) => {
        const selectedIds = selectedAttributeValueIds[attributeId] || [];
        allSelectedValueIds.push(...selectedIds);
      });

      const baseSlug = formDataSlug || slugifyProductTitle(formDataTitle) || 'prod';
      let sku = generateSkuFromSlug(baseSlug);

      if (allSelectedValueIds.length > 0) {
        const valueParts: string[] = [];
        selectedAttrs.forEach((attributeId) => {
          const attribute = attributes.find((a) => a.id === attributeId);
          if (!attribute) return;

          const selectedIds = selectedAttributeValueIds[attributeId] || [];
          selectedIds.forEach((valueId) => {
            const value = attribute.values.find((v) => v.id === valueId);
            if (value) {
              valueParts.push(value.value.toUpperCase().replace(/\s+/g, '-'));
            }
          });
        });

        if (valueParts.length > 0) {
          sku = `${generateSkuFromSlug(baseSlug)}-${valueParts.join('-')}`;
        }
      }

      const previousIds = existingAutoVariant?.selectedValueIds ?? [];
      const priceFromAdjustments = recomputeVariantPriceWithAdjustments(
        existingAutoVariant?.price ?? '',
        previousIds,
        allSelectedValueIds,
        attributes
      );
      const hasManualPrice =
        existingAutoVariant?.price !== undefined &&
        String(existingAutoVariant.price).trim() !== '';
      const adjustmentOnly = sumAttributeValuePriceAdjustments(attributes, allSelectedValueIds);
      const resolvedPrice = hasManualPrice
        ? priceFromAdjustments
        : adjustmentOnly > 0
          ? String(adjustmentOnly)
          : existingAutoVariant?.price || '';

      const autoVariant: GeneratedVariant = {
        id: variantId,
        selectedValueIds: allSelectedValueIds,
        price: resolvedPrice,
        compareAtPrice: existingAutoVariant?.compareAtPrice || '',
        stock: existingAutoVariant?.stock || '',
        sku: existingAutoVariant?.sku || sku,
        image: existingAutoVariant?.image || null,
      };

      const result = [autoVariant];
      logger.debug('✅ [VARIANT BUILDER] Variants updated:', {
        manuallyAdded: 0,
        autoGenerated: 1,
        total: result.length,
      });
      return result;
    });

    logger.debug('✅ [VARIANT BUILDER] Single variant generated with', selectedAttrs.length, 'attributes');
  };

  const applyToAllVariants = (field: 'price' | 'compareAtPrice' | 'stock' | 'sku', value: string) => {
    setGeneratedVariants((prev) =>
      prev.map((variant) => ({
        ...variant,
        [field]: value,
      }))
    );
  };

  useEffect(() => {
    if (isEditMode && productId && hasVariantsToLoad) {
      return;
    }

    if (selectedAttributesForVariants.size > 0) {
      generateVariantsFromAttributes();
    } else {
      if (!isEditMode) {
        setGeneratedVariants(() => []);
      }
    }
     
  }, [
    selectedAttributesForVariants,
    selectedAttributeValueIds,
    attributes,
    formDataSlug,
    formDataTitle,
    isEditMode,
    productId,
    hasVariantsToLoad,
  ]);

  return {
    generateVariantsFromAttributes,
    applyToAllVariants,
  };
}


