'use client';

import type { ChangeEvent } from 'react';
import { Card } from '@shop/ui';
import type {
  Category,
  Attribute,
  ProductLabel,
} from '../types';
import type { CurrencyCode } from '@/lib/currency';
import { BasicInformation } from './BasicInformation';
import { ProductImages } from './ProductImages';
import { ProductCategoriesSection } from './ProductCategoriesSection';
import { SimpleProductFields } from './SimpleProductFields';
import { ProductLabels } from './ProductLabels';
import { Publishing } from './Publishing';
import { FormActions } from './FormActions';
import { ProductCustomizationSection } from './ProductCustomizationSection';
import { ProductFoodTasteBadgesSection } from './ProductFoodTasteBadgesSection';
import type { PdpCustomizationFormState } from '../utils/pdp-customization-form';
import type { FoodTasteBadgeSelection } from '@/lib/product-food-taste-admin';

interface AddProductFormContentProps {
  formData: {
    title: string;
    slug: string;
    descriptionHtml: string;
    categoryIds: string[];
    primaryCategoryId: string;
    imageUrls: string[];
    featuredImageIndex: number;
    labels: ProductLabel[];
    featured: boolean;
  };
  simpleProductData: {
    price: string;
    compareAtPrice: string;
    sku: string;
    quantity: string;
  };
  categories: Category[];
  attributes: Attribute[];
  selectedPdpCustomizationAttributeIds: Set<string>;
  onSelectedPdpCustomizationAttributeIdsChange: (updater: (prev: Set<string>) => Set<string>) => void;
  pdpCustomizationForm: PdpCustomizationFormState;
  onPdpCustomizationFormChange: (
    updater: (prev: PdpCustomizationFormState) => PdpCustomizationFormState,
  ) => void;
  defaultCurrency: CurrencyCode;
  isEditMode: boolean;
  loading: boolean;
  imageUploadLoading: boolean;
  imageUploadError: string | null;
  categoriesExpanded: boolean;
  useNewCategory: boolean;
  newCategoryName: string;
  fileInputRef: React.RefObject<HTMLInputElement>;
  onTitleChange: (e: ChangeEvent<HTMLInputElement>) => void;
  onDescriptionChange: (e: ChangeEvent<HTMLTextAreaElement>) => void;
  onUploadImages: (event: ChangeEvent<HTMLInputElement>) => Promise<void>;
  onRemoveImage: (index: number) => void;
  onSetFeaturedImage: (index: number) => void;
  onCategoriesExpandedChange: (expanded: boolean) => void;
  onUseNewCategoryChange: (use: boolean) => void;
  onNewCategoryNameChange: (name: string) => void;
  onCategoryIdsChange: (ids: string[]) => void;
  onPrimaryCategoryIdChange: (id: string) => void;
  onPriceChange: (value: string) => void;
  onCompareAtPriceChange: (value: string) => void;
  onQuantityChange: (value: string) => void;
  onAddLabel: () => void;
  onRemoveLabel: (index: number) => void;
  onUpdateLabel: (index: number, field: keyof ProductLabel, value: any) => void;
  onFeaturedChange: (featured: boolean) => void;
  isClothingCategory: () => boolean;
  generateSlug: (text: string) => string;
  handleSubmit: (e: React.FormEvent) => void;
  foodTasteBadges: FoodTasteBadgeSelection;
  onFoodTasteBadgesChange: (next: FoodTasteBadgeSelection) => void;
}

export function AddProductFormContent({
  formData,
  simpleProductData,
  categories,
  attributes,
  selectedPdpCustomizationAttributeIds,
  onSelectedPdpCustomizationAttributeIdsChange,
  pdpCustomizationForm,
  onPdpCustomizationFormChange,
  defaultCurrency,
  isEditMode,
  loading,
  imageUploadLoading,
  imageUploadError,
  categoriesExpanded,
  useNewCategory,
  newCategoryName,
  fileInputRef,
  onTitleChange,
  onDescriptionChange,
  onUploadImages,
  onRemoveImage,
  onSetFeaturedImage,
  onCategoriesExpandedChange,
  onUseNewCategoryChange,
  onNewCategoryNameChange,
  onCategoryIdsChange,
  onPrimaryCategoryIdChange,
  onPriceChange,
  onCompareAtPriceChange,
  onQuantityChange,
  onAddLabel,
  onRemoveLabel,
  onUpdateLabel,
  onFeaturedChange,
  isClothingCategory,
  generateSlug,
  handleSubmit,
  foodTasteBadges,
  onFoodTasteBadgesChange,
}: AddProductFormContentProps) {
  const showFoodTasteBadges = !isClothingCategory();

  return (
    <Card className="p-6 pb-24 sm:pb-24">
      <form onSubmit={handleSubmit} className="space-y-14">
        <BasicInformation
          title={formData.title}
          slug={formData.slug}
          descriptionHtml={formData.descriptionHtml}
          onTitleChange={onTitleChange}
          onDescriptionChange={onDescriptionChange}
          slugAutoGenerated={!isEditMode}
        />

        <ProductImages
          imageUrls={formData.imageUrls}
          featuredImageIndex={formData.featuredImageIndex}
          imageUploadLoading={imageUploadLoading}
          imageUploadError={imageUploadError}
          fileInputRef={fileInputRef}
          onUploadImages={onUploadImages}
          onRemoveImage={onRemoveImage}
          onSetFeaturedImage={onSetFeaturedImage}
        />

        <ProductCategoriesSection
          categories={categories}
          categoryIds={formData.categoryIds}
          categoriesExpanded={categoriesExpanded}
          useNewCategory={useNewCategory}
          newCategoryName={newCategoryName}
          onCategoriesExpandedChange={onCategoriesExpandedChange}
          onUseNewCategoryChange={onUseNewCategoryChange}
          onNewCategoryNameChange={onNewCategoryNameChange}
          onCategoryIdsChange={onCategoryIdsChange}
          onPrimaryCategoryIdChange={onPrimaryCategoryIdChange}
          isClothingCategory={isClothingCategory}
        />

        {showFoodTasteBadges ? (
          <ProductFoodTasteBadgesSection
            selection={foodTasteBadges}
            onSelectionChange={onFoodTasteBadgesChange}
          />
        ) : null}

        <ProductCustomizationSection
          attributes={attributes}
          selectedAttributeIds={selectedPdpCustomizationAttributeIds}
          onSelectedAttributeIdsChange={onSelectedPdpCustomizationAttributeIdsChange}
          formState={pdpCustomizationForm}
          onFormStateChange={onPdpCustomizationFormChange}
        />

        <SimpleProductFields
          price={simpleProductData.price}
          compareAtPrice={simpleProductData.compareAtPrice}
          sku={simpleProductData.sku}
          quantity={simpleProductData.quantity}
          defaultCurrency={defaultCurrency}
          onPriceChange={onPriceChange}
          onCompareAtPriceChange={onCompareAtPriceChange}
          onQuantityChange={onQuantityChange}
          skuAutoGenerated={!isEditMode}
        />

        <ProductLabels
          labels={formData.labels}
          onAddLabel={onAddLabel}
          onRemoveLabel={onRemoveLabel}
          onUpdateLabel={onUpdateLabel}
        />

        <Publishing featured={formData.featured} onFeaturedChange={onFeaturedChange} />

        <FormActions loading={loading} isEditMode={isEditMode} />
      </form>
    </Card>
  );
}

