'use client';

import type { ChangeEvent } from 'react';
import { Input } from '@shop/ui';
import { useTranslation } from '../../../../../lib/i18n-client';

interface BasicInformationProps {
  title: string;
  slug: string;
  descriptionHtml: string;
  onTitleChange: (e: ChangeEvent<HTMLInputElement>) => void;
  onDescriptionChange: (e: ChangeEvent<HTMLTextAreaElement>) => void;
  slugAutoGenerated?: boolean;
}

export function BasicInformation({
  title,
  slug,
  descriptionHtml,
  onTitleChange,
  onDescriptionChange,
  slugAutoGenerated = true,
}: BasicInformationProps) {
  const { t } = useTranslation();

  return (
    <div>
      <h2 className="text-xl font-semibold text-gray-900 mb-4">{t('admin.products.add.basicInformation')}</h2>
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('admin.products.add.title')} *
          </label>
          <Input
            type="text"
            value={title}
            onChange={onTitleChange}
            required
            placeholder={t('admin.products.add.productTitlePlaceholder')}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('admin.products.add.slug')}
            {slugAutoGenerated ? (
              <span className="ml-2 text-xs font-normal text-gray-500">
                ({t('admin.products.add.autoGenerated')})
              </span>
            ) : null}
          </label>
          <Input
            type="text"
            value={slug}
            readOnly={slugAutoGenerated}
            placeholder={t('admin.products.add.productSlugPlaceholder')}
            className={slugAutoGenerated ? 'bg-gray-50 text-gray-700 cursor-default' : undefined}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('admin.products.add.description')}
          </label>
          <textarea
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            rows={6}
            value={descriptionHtml}
            onChange={onDescriptionChange}
            placeholder={t('admin.products.add.productDescriptionPlaceholder')}
          />
        </div>
      </div>
    </div>
  );
}


