'use client';

import { Input } from '@shop/ui';
import { useTranslation } from '../../../../../lib/i18n-client';
import { CURRENCIES, type CurrencyCode } from '../../../../../lib/currency';

interface SimpleProductFieldsProps {
  price: string;
  compareAtPrice: string;
  sku: string;
  quantity: string;
  defaultCurrency: CurrencyCode;
  onPriceChange: (value: string) => void;
  onCompareAtPriceChange: (value: string) => void;
  onQuantityChange: (value: string) => void;
  skuAutoGenerated?: boolean;
}

export function SimpleProductFields({
  price,
  compareAtPrice,
  sku,
  quantity,
  defaultCurrency,
  onPriceChange,
  onCompareAtPriceChange,
  onQuantityChange,
  skuAutoGenerated = true,
}: SimpleProductFieldsProps) {
  const { t } = useTranslation();

  return (
    <div>
      <h2 className="text-xl font-semibold text-gray-900 mb-4">{t('admin.products.add.productVariants')}</h2>
      <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Price */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.price')} *
            </label>
            <div className="flex items-center gap-2">
              <Input
                type="number"
                value={price}
                onChange={(e) => onPriceChange(e.target.value)}
                placeholder={t('admin.products.add.pricePlaceholder')}
                className="flex-1"
                min="0"
                step="0.01"
                required
              />
              <span className="text-sm text-gray-500 whitespace-nowrap">{CURRENCIES[defaultCurrency].symbol}</span>
            </div>
          </div>

          {/* Compare At Price */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.compareAtPrice')}
            </label>
            <div className="flex items-center gap-2">
              <Input
                type="number"
                value={compareAtPrice}
                onChange={(e) => onCompareAtPriceChange(e.target.value)}
                placeholder={t('admin.products.add.pricePlaceholder')}
                className="flex-1"
                min="0"
                step="0.01"
              />
              <span className="text-sm text-gray-500 whitespace-nowrap">{CURRENCIES[defaultCurrency].symbol}</span>
            </div>
          </div>

          {/* SKU */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.sku')}
              {skuAutoGenerated ? (
                <span className="ml-2 text-xs font-normal text-gray-500">
                  ({t('admin.products.add.autoGenerated')})
                </span>
              ) : null}
            </label>
            <Input
              type="text"
              value={sku}
              readOnly={skuAutoGenerated}
              placeholder={t('admin.products.add.autoGenerated')}
              className={`w-full ${skuAutoGenerated ? 'bg-gray-50 text-gray-700 cursor-default' : ''}`}
            />
          </div>

          {/* Quantity */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.quantity')}
            </label>
            <Input
              type="number"
              value={quantity}
              onChange={(e) => onQuantityChange(e.target.value)}
              placeholder={t('admin.products.add.quantityPlaceholder')}
              className="w-full"
              min="0"
            />
          </div>
        </div>
      </div>
    </div>
  );
}


